const oracledb = require('oracledb');
require('dotenv').config();

async function run() {
  let connection;
  try {
    connection = await oracledb.getConnection({
      user: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_HOST + ':' + process.env.DB_PORT + '/' + process.env.DB_SERVICE_NAME
    });
    
    const sql = `
CREATE OR REPLACE PROCEDURE SP_THANH_TOAN_DON_HANG (
    p_MADONHANG IN NUMBER,
    p_PHUONGTHUCTHANHTHOAN IN NVARCHAR2
) AS
    v_MADOITAC NUMBER;
    v_MACUAHANG NUMBER;
    v_MANHANVIEN NUMBER;
    v_TONGTIENTAMTINH NUMBER;
    v_DIEMMUONDUNG NUMBER;
    v_DIEMTICHDUOC NUMBER;
    v_MAHOADON NUMBER;
    v_MATAIKHOAN NUMBER;
    v_MAKHO NUMBER;
    v_SOPHIEUXUAT NVARCHAR2(100);
BEGIN
    SELECT MADOITAC, MACUAHANG, MANHANVIEN, TONGTIENTAMTINH, DIEMMUONDUNG
    INTO v_MADOITAC, v_MACUAHANG, v_MANHANVIEN, v_TONGTIENTAMTINH, v_DIEMMUONDUNG
    FROM DON_HANG
    WHERE MADONHANG = p_MADONHANG;
    v_DIEMTICHDUOC := TRUNC(NVL(v_TONGTIENTAMTINH, 0) / 1000);
    IF p_PHUONGTHUCTHANHTHOAN = 'Tiền mặt' THEN
        v_MATAIKHOAN := 111;
    ELSE
        v_MATAIKHOAN := 112;
    END IF;
    BEGIN
        SELECT MAKHO
        INTO v_MAKHO
        FROM (
            SELECT MAKHO FROM KHO WHERE MACUAHANG = v_MACUAHANG AND MAKHO IS NOT NULL
        )
        WHERE ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Lỗi hệ thống: Cửa hàng ' || v_MACUAHANG || ' chưa cấu hình kho xuất hàng.');
    END;
    INSERT INTO HOA_DON_BAN_HANG (
        MADOITAC, MADONHANG, MACUAHANG, NGAYBAN, TONGTIEN,
        DIEMTICHDUOC, DIEMSUDUNG, PHUONGTHUCTHANHTHOAN, MANHANVIEN
    ) VALUES (
        v_MADOITAC, p_MADONHANG, v_MACUAHANG, SYSTIMESTAMP, v_TONGTIENTAMTINH,
        v_DIEMTICHDUOC, v_DIEMMUONDUNG, p_PHUONGTHUCTHANHTHOAN, v_MANHANVIEN
    ) RETURNING MAHOADON INTO v_MAHOADON;
    INSERT INTO CHI_TIET_HOA_DON_BAN_HANG (
        MASANPHAM, MAHOADON, SOLUONG, DONGIA, THANHTIEN
    )
    SELECT MASANPHAM, v_MAHOADON, SOLUONG, DONGIA, THANHTIEN
    FROM CHI_TIET_DON_HANG
    WHERE MADONHANG = p_MADONHANG;
    v_SOPHIEUXUAT := 'PXK-' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MI') || '-' || v_MAHOADON;

    INSERT INTO PHIEU_KHO (
        SOPHIEU, LOAIPHIEU, MAHOADON, NGAYLAP, NGAYTHUCPHE, 
        KHODI, KHODEN, DOITAC, TONGGIATRIPHIEU, NGUOIPHUTRACH, TRANGTHAI
    ) VALUES (
        v_SOPHIEUXUAT, 'Xuất kho bán hàng', v_MAHOADON, SYSTIMESTAMP, SYSTIMESTAMP,
        v_MAKHO, NULL, v_MADOITAC, v_TONGTIENTAMTINH, v_MANHANVIEN, 'Đã xuất'
    );
    FOR rec IN (
        SELECT MASANPHAM, SOLUONG, DONGIA, THANHTIEN
        FROM CHI_TIET_DON_HANG
        WHERE MADONHANG = p_MADONHANG
    ) LOOP
        INSERT INTO CHI_TIET_PHIEU (
            SOPHIEU, MASANPHAM, SOLUONG, DONGIA, THANHTIEN
        ) VALUES (
            v_SOPHIEUXUAT, rec.MASANPHAM, rec.SOLUONG, rec.DONGIA, rec.THANHTIEN
        );
    END LOOP;
    UPDATE DON_HANG
    SET TRANGTHAI = 'Đã thanh toán'
    WHERE MADONHANG = p_MADONHANG;
    UPDATE KHACH_HANG
    SET DIEMTICHLUY = NVL(DIEMTICHLUY,0) + v_DIEMTICHDUOC - NVL(v_DIEMMUONDUNG,0)
    WHERE MADOITAC = v_MADOITAC;
    
    DECLARE
        v_doanhthu NUMBER;
        v_thuevat NUMBER;
    BEGIN
        v_doanhthu := ROUND(v_TONGTIENTAMTINH / 1.1);
        v_thuevat := v_TONGTIENTAMTINH - v_doanhthu;

        -- 1. Ghi nhận Nợ TK 111/112
        INSERT INTO GIAO_DICH_TIEN (
            MACUAHANG, MATAIKHOAN, LOAIGIAODICH, SOTIEN, NGAYGIAODICH, MAHOADONBAN, GHICHU
        ) VALUES (
            v_MACUAHANG, v_MATAIKHOAN, 'Thu tiền bán hàng', v_TONGTIENTAMTINH, SYSTIMESTAMP, v_MAHOADON, 'Khách thanh toán POS (Đơn #' || TO_CHAR(p_MADONHANG) || ')'
        );
        UPDATE TAI_KHOAN SET SODUHIENTAI = NVL(SODUHIENTAI,0) + v_TONGTIENTAMTINH WHERE MATAIKHOAN = v_MATAIKHOAN;

        -- 2. Ghi nhận Có TK 5111
        INSERT INTO GIAO_DICH_TIEN (
            MACUAHANG, MATAIKHOAN, LOAIGIAODICH, SOTIEN, NGAYGIAODICH, MAHOADONBAN, GHICHU
        ) VALUES (
            v_MACUAHANG, 5111, 'Ghi nhận doanh thu', v_doanhthu, SYSTIMESTAMP, v_MAHOADON, 'Doanh thu bán hàng POS (Chưa VAT) (Đơn #' || TO_CHAR(p_MADONHANG) || ')'
        );
        UPDATE TAI_KHOAN SET SODUHIENTAI = NVL(SODUHIENTAI,0) + v_doanhthu WHERE MATAIKHOAN = 5111;

        -- 3. Ghi nhận Có TK 3331
        IF v_thuevat > 0 THEN
            INSERT INTO GIAO_DICH_TIEN (
                MACUAHANG, MATAIKHOAN, LOAIGIAODICH, SOTIEN, NGAYGIAODICH, MAHOADONBAN, GHICHU
            ) VALUES (
                v_MACUAHANG, 3331, 'Ghi nhận thuế VAT', v_thuevat, SYSTIMESTAMP, v_MAHOADON, 'Thuế GTGT 10% đầu ra (Đơn #' || TO_CHAR(p_MADONHANG) || ')'
            );
            UPDATE TAI_KHOAN SET SODUHIENTAI = NVL(SODUHIENTAI,0) + v_thuevat WHERE MATAIKHOAN = 3331;
        END IF;
    END;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_THANH_TOAN_DON_HANG;
    `;
    
    await connection.execute(sql);
    console.log('SP_THANH_TOAN_DON_HANG successfully replaced in DB.');
  } catch (err) {
    console.error(err);
  } finally {
    if (connection) await connection.close();
  }
}
run();
