import React, { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    'settings.title': 'Cài Đặt Hệ Thống',
    'settings.language': 'Ngôn ngữ',
    'settings.theme': 'Giao diện',
    'settings.printer': 'Máy in hóa đơn',
    'settings.notifications': 'Thông báo',
    'settings.security': 'Bảo mật',
    'settings.coming_soon': 'Tính năng đang phát triển',
    'common.success': 'Thành công',
    'common.error': 'Lỗi',
    'common.loading': 'Đang tải...',
    'common.logout': 'Đăng xuất',
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.pos': 'Bán hàng (POS)',
    'nav.customers': 'Đối tác',
    'nav.inventory': 'Tồn kho',
    'nav.returns': 'Đổi trả',
    'nav.logistics': 'Phiếu kho',
    'nav.time_management': 'Chấm công & Phép',
    'nav.finance': 'Thu chi',
    'nav.procurement': 'Mua hàng',
    'nav.hr': 'Nhân sự',
    'nav.multi_store': 'Chi nhánh',
    'nav.settings': 'Cài đặt',
    'nav.menu_main': 'DANH MỤC CHÍNH',
    'nav.menu_ops': 'VẬN HÀNH',
    // Dashboard
    'dash.greeting_morning': 'Chào buổi sáng',
    'dash.greeting_afternoon': 'Chào buổi chiều',
    'dash.greeting_evening': 'Chào buổi tối',
    'dash.admin': 'Quản trị viên',
    'dash.loading': 'Đang tổng hợp dữ liệu toàn hệ thống...',
    'dash.kpi_revenue': 'Doanh Thu (Tháng)',
    'dash.kpi_orders': 'Đơn Hàng (Tháng)',
    'dash.kpi_customers': 'Tổng Khách Hàng',
    'dash.kpi_conversion': 'Tỷ lệ chuyển đổi',
    'dash.chart_revenue': 'Doanh thu 6 tháng qua',
    'dash.chart_revenue_empty': 'Chưa có giao dịch bán hàng nào trong 6 tháng qua.',
    'dash.chart_structure': 'Cơ cấu bán hàng',
    'dash.chart_structure_sub': 'Tỷ trọng doanh số theo thương hiệu',
    'dash.recent_activities': 'Hoạt động gần đây',
    'dash.no_activities': 'Chưa có hoạt động nào được ghi nhận.',
    'dash.chart_weekly_orders': 'Lượng đơn hàng trong tuần',
    'dash.today': 'Hôm nay',
    'dash.yesterday': 'Hôm qua',
    'dash.revenue': 'Doanh thu',
    'dash.sales': 'Doanh số',
    // HR
    'hr.hr_management': 'Quản lý nhân sự',
    'hr.staff': 'Nhân viên',
    'hr.attendance': 'Chấm công',
    'hr.leave': 'Nghỉ phép',
    'hr.payroll': 'Bảng lương',
    'hr.add_staff': 'Thêm nhân viên',
    'hr.calc_title': 'Bảng Tính Lương Chi Tiết',
    'hr.base_salary': 'Lương cơ bản',
    'hr.work_days': 'Công thực tế',
    'hr.total_received': 'Tổng nhận',
    'hr.status': 'Trạng thái',
    'hr.actions': 'Hành động',
    'hr.calc_button': 'Lập phiếu lương',
    'hr.payment_button': 'Tạo phiếu chi',
    'hr.insurance_worker': 'Khoản trích từ lương (10.5%)',
    'hr.insurance_company': 'DN đóng thêm (21.5%)',
    'hr.net_salary': 'Thực lĩnh nhân viên',
    'hr.total_cost': 'Tổng chi phí DN',
    'hr.insurance_note': 'Mức lương đóng bảo hiểm tối đa được giới hạn ở 36,000,000đ.',
    'hr.payroll_month': 'Bảng lương tháng',
    'hr.payroll_desc': 'Chuẩn công: 26 ngày/tháng. Lương thực nhận = (Lương CB / 26 * Công) + Tăng ca.',
    // Finance
    'fin.title': 'Tài Chính & Kế Toán',
    'fin.tab_overview': 'Tổng Quan Sổ Cái',
    'fin.tab_payables': 'Công Nợ & Chi Tiền',
    'fin.total_assets': 'Tổng Tài Sản',
    'fin.total_liabilities': 'Nợ Phải Trả',
    'fin.total_revenue': 'Doanh Thu',
    'fin.loading': 'Đang hợp nhất sổ cái...',
    'fin.unpaid': 'Chưa thanh toán',
    'fin.paid': 'Đã thanh toán',
    'fin.cash': 'Tiền mặt',
    'fin.bank': 'Ngân hàng',
    'fin.success_pay': 'Thanh toán thành công!',
    'fin.total_unpaid': 'Tổng nợ chưa trả (NCC & Lương)',
    'fin.history': 'Lịch Sử Chi Tiền (Đã thanh toán)',
    'fin.doc_type': 'Loại / Mã',
    'fin.entity': 'Đối Tượng',
    'fin.date_created': 'Ngày Lập',
    'fin.amount': 'Số Tiền',
    'fin.action': 'Nghiệp Vụ',
    'fin.pending_pay': 'Chờ chi',
    'fin.paid_status': 'Đã chi',
    'fin.pay_button': 'Thanh Toán',
    'fin.done': 'Hoàn tất',
    'fin.confirm_pay': 'Xác nhận thanh toán',
    'fin.pay_to_supplier': 'Chi trả cho NCC',
    'fin.pay_amount': 'Số tiền thanh toán',
    'fin.expense_type': 'Loại chi',
    'fin.note': 'Nội dung / Ghi chú',
    'fin.account': 'Tài khoản chi',
    'fin.time': 'Thời gian',
    'fin.salary_expense': 'LƯƠNG NHÂN VIÊN',
    'fin.supplier_debt': 'NỢ NHÀ CUNG CẤP',
    'fin.other_expense': 'CHI KHÁC',
    'fin.no_history': 'Chưa có dữ liệu chi tiền.',
    'fin.total_paid_history': 'Đã chi trả (Lịch sử)',
    'fin.docs_payables': 'Chứng Từ Phải Trả & Thanh Toán',
    // Inventory
    'inv.title': 'Quản Lý Kho Hàng',
    'inv.total_items': 'Tổng mặt hàng',
    'inv.active': 'Đang kinh doanh',
    'inv.low_stock_status': 'Sắp hết hàng',
    'inv.out_of_stock_status': 'Hết hàng',
    'inv.add_product': 'Thêm sản phẩm',
    'inv.search': 'Tìm kiếm sản phẩm...',
    'inv.stock_status': 'Trình trạng kho',
    'inv.in_stock': 'Còn hàng',
    'inv.low_stock': 'Sắp hết hàng',
    'inv.out_of_stock': 'Hết hàng',
    'inv.category': 'Danh mục',
    'inv.price': 'Giá bán',
    'inv.stock': 'Tồn kho',
    'inv.action': 'Hành động',
    // Procurement
    'proc.title': 'Quản Lý Mua Hàng',
    'proc.add_order': 'Tạo đơn mua',
    'proc.supplier': 'Nhà cung cấp',
    'proc.total_amount': 'Tổng tiền',
    'proc.order_status': 'Trạng thái đơn',
    'proc.pending': 'Chờ duyệt',
    'proc.approved': 'Đã duyệt',
    'proc.received': 'Đã nhập kho',
    'proc.invoice_po': 'Hóa Đơn (PO)',
    'proc.date_received': 'Ngày Nhập',
    'proc.ticket_code': 'Mã Phiếu Kho',
    'proc.warehouse_status': 'Trạng Thái Kho',
    'proc.awaiting_delivery': 'Chờ giao hàng',
    'proc.no_orders': 'Chưa có đơn nhập hàng nào trong hệ thống.',
    // POS
    'pos.title': 'Điểm Bán Hàng (POS)',
    'pos.cart': 'Giỏ hàng',
    'pos.checkout': 'Thanh toán',
    'pos.total': 'Tổng cộng',
    'pos.customer': 'Khách hàng',
    'pos.search_phone': 'Tìm theo số điện thoại...',
    'pos.search_btn': 'Tìm',
    'pos.subtotal': 'Tạm tính',
    'pos.tax': 'VAT (10%)',
    'pos.total_payment': 'Tổng thanh toán',
    'pos.cash': 'Tiền mặt',
    'pos.bank_qr': 'QR Ngân hàng',
    'pos.pay': 'Thanh toán',
    'pos.print_receipt': 'In hóa đơn',
    'pos.guest': 'Khách vãng lai',
    'pos.skip': 'Bỏ qua',
    'pos.phone': 'SĐT',
    'pos.not_exist': 'chưa có',
    'pos.enter_new_name': 'Nhập tên khách hàng mới...',
    'pos.create_and_select': '+ Tạo & Chọn',
    'pos.creating': 'Đang tạo...',
    // Partners
    'part.title': 'Quản Lý Đối Tác',
    'part.customers': 'Khách hàng',
    'part.suppliers': 'Nhà cung cấp',
    // Time Management
    'time.title': 'Chấm Công & Nghỉ Phép',
    'time.check_in': 'Vào Ca',
    'time.check_out': 'Kết Ca',
    'time.toast_in_success': 'Điểm danh thành công!',
    'time.toast_in_desc': 'Chúc bạn một ca làm việc tràn đầy năng lượng! ✨',
    'time.toast_out_desc': 'Cảm ơn bạn vì một ngày làm việc tuyệt vời. Nghỉ ngơi tốt nhé! 🌙',
    'time.toast_err_conn': 'Lỗi kết nối máy chủ!',
    'time.leave_annual': 'Nghỉ phép năm (Có lương)',
    'time.leave_sick': 'Nghỉ ốm',
    'time.leave_unpaid': 'Nghỉ việc riêng (Không lương)',
    'time.date_err': 'Lỗi ngày tháng',
    'time.date_err_desc': 'Ngày kết thúc phải lớn hơn hoặc bằng ngày bắt đầu!',
    'time.submit_success': 'Gửi đơn thành công!',
    'time.submit_err': 'Lỗi khi gửi đơn!',
    'time.history_title': 'Lịch sử chấm công chi tiết',
    'time.col_date': 'Ngày',
    'time.col_in': 'Giờ vào',
    'time.col_out': 'Giờ ra',
    'time.col_work': 'Giờ làm',
    'time.col_ot': 'Tăng ca',
    'time.col_status': 'Trạng thái',
    'time.col_notes': 'Ghi chú',
    'time.hours': 'giờ',
    'time.working': 'Đang làm việc',
    'time.no_attendance': 'Chưa có dữ liệu chấm công.',
    'time.create_leave': 'Tạo Đơn Xin Nghỉ Phép',
    'time.leave_type': 'Loại nghỉ phép',
    'time.from_date': 'Từ ngày',
    'time.to_date': 'Đến ngày',
    'time.total_days': 'Tổng số ngày',
    'time.auto_calc': '(Tự động tính)',
    'time.reason': 'Lý do chi tiết',
    'time.submit_leave': 'Gửi Đơn Cho Quản Lý',
    'time.submitted_leaves': 'Danh sách đơn đã gửi',
    'time.leave_col_type': 'Loại nghỉ',
    'time.leave_col_time': 'Thời gian',
    'time.leave_col_days': 'Số ngày',
    'time.days_count': 'ngày',
    'time.pending': 'Chờ duyệt',
    'time.approved': 'Đã duyệt',
    'time.rejected': 'Từ chối',
    'time.no_leaves': 'Bạn chưa gửi đơn xin nghỉ phép nào.',
    // Multi-Store
    'store.title': 'Hệ Thống Chi Nhánh',
    'store.add': 'Thêm Chi Nhánh',
    'store.add_coming': 'Tính năng thêm chi nhánh đang được hoàn thiện',
    'store.active': 'Hoạt động',
    'store.staff': 'Nhân sự',
    'store.staff_member': 'thành viên',
    'store.warehouse': 'Kho bãi',
    'store.warehouse_location': 'địa điểm',
    'store.details': 'Chi tiết',
    'store.manager': 'Quản lý trực tiếp',
    'store.no_manager': 'Chưa gán quản lý',
    'store.contact': 'Thông tin liên lạc',
    'store.recent_activities': 'Các hoạt động gần đây',
    'store.sync_msg': 'Đã đồng bộ tồn kho từ Kho Tổng',
    'store.minutes_ago': '15 phút trước',
    'store.manage_staff': 'Quản lý nhân sự',
    'store.view_layout': 'Xem sơ đồ kho',
    'store.recommendation': 'Hệ thống gợi ý',
    'store.recommendation_msg': 'Chi nhánh này đang có hiệu suất cao hơn 15% so với cùng kỳ tháng trước. Nên cân nhắc mở rộng thêm kho bãi.',
    // Logistics
    'log.title': 'Điều Phối & Phiếu Kho',
    'log.err_load': 'Lỗi tải dữ liệu phiếu kho!',
    'log.err_full_info': 'Vui lòng nhập đầy đủ thông tin!',
    'log.success_transfer': 'Tạo phiếu chuyển kho thành công!',
    'log.err_connection': 'Lỗi kết nối server!',
    'log.success_approve': 'Đã duyệt nhập kho thành công! Tồn kho đã được cộng.',
    'log.err_approve': 'Lỗi xử lý duyệt kho!',
    'log.code': 'Mã Phiếu',
    'log.type': 'Loại Phiếu',
    'log.source': 'Từ (Nguồn)',
    'log.destination': 'Đến (Đích)',
    'log.date': 'Ngày Lập',
    'log.total_value': 'Tổng Giá Trị',
    'log.action_status': 'Hành Động / Trạng Thái',
    'log.loading': 'Đang tải dữ liệu phiếu kho...',
    'log.no_data': 'Chưa có dữ liệu phiếu kho nào.',
    'log.confirm_intake': 'Xác nhận Nhập Kho',
    'log.completed': 'Đã hoàn tất',
    'log.confirm_intake_question': 'Bạn có chắc chắn hàng đã giao đủ và muốn tiến hành nhập kho cho phiếu không? Số lượng tồn kho sẽ được cộng tự động.',
    'log.cancel': 'Hủy bỏ',
    'log.processing': 'Đang xử lý...',
    'log.confirm_intake_btn': 'Xác Nhận Nhập',
    'log.create_transfer_title': 'Tạo Phiếu Chuyển Kho',
    'log.from_warehouse': 'Kho Đi',
    'log.select_from_warehouse': 'Chọn kho đi',
    'log.to_warehouse': 'Kho Đến',
    'log.select_to_warehouse': 'Chọn kho đến',
    'log.product': 'Sản Phẩm',
    'log.select_product': 'Chọn sản phẩm',
    'log.stock_lbl': 'Tồn',
    'log.transfer_qty': 'Số Lượng Chuyển',
    'log.system_error': 'Lỗi hệ thống',
    // Returns
    'ret.title': 'Quản Lý Đổi Trả',
    'ret.create_ticket_pos': 'Tạo Phiếu Trả Hàng (POS)',
    'ret.approve_requests': 'Duyệt Yêu Cầu',
    'ret.lookup_invoice': 'Tra cứu hóa đơn',
    'ret.invoice_placeholder': 'Mã hóa đơn (Ví dụ: INV-1)...',
    'ret.searching': 'Đang tìm...',
    'ret.check_btn': 'Kiểm Tra',
    'ret.customer': 'Khách hàng',
    'ret.purchase_date': 'Ngày mua',
    'ret.product': 'Sản Phẩm',
    'ret.qty_ratio': 'SL Trả / Mua',
    'ret.restock': 'Nhập lại kho?',
    'ret.note_to_manager': 'Ghi chú cho Quản lý (Lý do trả)',
    'ret.note_placeholder': 'VD: Sản phẩm bị lỗi seal, cần hoàn tiền...',
    'ret.total_refund': 'Tổng tiền sẽ hoàn',
    'ret.submit_request': 'Gửi Yêu Cầu Chờ Duyệt',
    'ret.no_requests': 'Chưa có yêu cầu đổi trả nào.',
    'ret.pending_msg': 'Yêu cầu chờ duyệt',
    'ret.completed_msg': 'Yêu cầu đã hoàn tất',
    'ret.rejected_msg': 'Yêu cầu đã từ chối',
    'ret.reject_btn': 'Từ chối',
    'ret.complete_btn': 'Hoàn tất',
    'ret.amount_to_refund': 'Số tiền cần hoàn',
    'ret.success_submit': 'Đã gửi Yêu cầu trả hàng cho Quản lý!',
    'ret.success_approve': 'Đã hoàn tất phiếu thành công!',
    'ret.success_reject': 'Đã từ chối phiếu thành công!',
    'ret.err_select_product': 'Vui lòng chọn sản phẩm muốn trả!',
    'ret.err_connection': 'Lỗi kết nối máy chủ!',
    'ret.err_not_found': 'Không tìm thấy hóa đơn',
    'ret.reason_lbl': 'Lý do',
    'ret.no_reason': 'Không có',
  },
  en: {
    'settings.title': 'System Settings',
    'settings.language': 'Language',
    'settings.theme': 'Appearance',
    'settings.printer': 'Invoice Printer',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.coming_soon': 'Feature coming soon',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.loading': 'Loading...',
    'common.logout': 'Logout',
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.pos': 'Sales (POS)',
    'nav.customers': 'Partners',
    'nav.inventory': 'Inventory',
    'nav.returns': 'Returns',
    'nav.logistics': 'Inventory Receipts',
    'nav.time_management': 'Attendance',
    'nav.finance': 'Finance',
    'nav.procurement': 'Procurement',
    'nav.hr': 'Human Resources',
    'nav.multi_store': 'Branches',
    'nav.settings': 'Settings',
    'nav.menu_main': 'MAIN MENU',
    'nav.menu_ops': 'OPERATIONS',
    // Dashboard
    'dash.greeting_morning': 'Good morning',
    'dash.greeting_afternoon': 'Good afternoon',
    'dash.greeting_evening': 'Good evening',
    'dash.admin': 'Administrator',
    'dash.loading': 'Aggregating system-wide data...',
    'dash.kpi_revenue': 'Revenue (Month)',
    'dash.kpi_orders': 'Orders (Month)',
    'dash.kpi_customers': 'Total Customers',
    'dash.kpi_conversion': 'Conversion Rate',
    'dash.chart_revenue': 'Revenue (Last 6 Months)',
    'dash.chart_revenue_empty': 'No sales transactions in the last 6 months.',
    'dash.chart_structure': 'Sales Structure',
    'dash.chart_structure_sub': 'Sales proportion by brand',
    'dash.recent_activities': 'Recent Activities',
    'dash.no_activities': 'No activities recorded yet.',
    'dash.chart_weekly_orders': 'Weekly Order Volume',
    'dash.today': 'Today',
    'dash.yesterday': 'Yesterday',
    'dash.revenue': 'Revenue',
    'dash.sales': 'Sales',
    // HR
    'hr.hr_management': 'Human Resource Management',
    'hr.staff': 'Staff',
    'hr.attendance': 'Attendance',
    'hr.leave': 'Leave Requests',
    'hr.payroll': 'Payroll',
    'hr.add_staff': 'Add Staff',
    'hr.calc_title': 'Detailed Salary Calculation',
    'hr.base_salary': 'Base Salary',
    'hr.work_days': 'Actual Workdays',
    'hr.total_received': 'Total Received',
    'hr.status': 'Status',
    'hr.actions': 'Actions',
    'hr.calc_button': 'Calculate Salary',
    'hr.payment_button': 'Create Payment',
    'hr.insurance_worker': 'Worker Deductions (10.5%)',
    'hr.insurance_company': 'Company Contributions (21.5%)',
    'hr.net_salary': 'Net Salary',
    'hr.total_cost': 'Total Cost',
    'hr.insurance_note': 'Insurance base salary is capped at 36,000,000 VND.',
    'hr.payroll_month': 'Payroll for Month',
    'hr.payroll_desc': 'Standard workdays: 26 days/month. Net salary = (Base Salary / 26 * Workdays) + Overtime.',
    // Finance
    'fin.title': 'Finance & Accounting',
    'fin.tab_overview': 'General Ledger Overview',
    'fin.tab_payables': 'Payables & Payments',
    'fin.total_assets': 'Total Assets',
    'fin.total_liabilities': 'Total Liabilities',
    'fin.total_revenue': 'Total Revenue',
    'fin.loading': 'Consolidating general ledger...',
    'fin.unpaid': 'Unpaid',
    'fin.paid': 'Paid',
    'fin.cash': 'Cash',
    'fin.bank': 'Bank',
    'fin.success_pay': 'Payment successful!',
    'fin.total_unpaid': 'Total Unpaid (Supplier & Salary)',
    'fin.history': 'Payment History (Paid)',
    'fin.doc_type': 'Type / Code',
    'fin.entity': 'Entity',
    'fin.date_created': 'Date Created',
    'fin.amount': 'Amount',
    'fin.action': 'Action',
    'fin.pending_pay': 'Pending',
    'fin.paid_status': 'Paid',
    'fin.pay_button': 'Pay',
    'fin.done': 'Done',
    'fin.confirm_pay': 'Confirm Payment',
    'fin.pay_to_supplier': 'Pay to Supplier',
    'fin.pay_amount': 'Payment Amount',
    'fin.expense_type': 'Expense Type',
    'fin.note': 'Description / Note',
    'fin.account': 'Payment Account',
    'fin.time': 'Time',
    'fin.salary_expense': 'STAFF SALARY',
    'fin.supplier_debt': 'SUPPLIER DEBT',
    'fin.other_expense': 'OTHER EXPENSE',
    'fin.no_history': 'No payment history available.',
    'fin.total_paid_history': 'Total Paid (History)',
    'fin.docs_payables': 'Payables & Payments Documents',
    // Inventory
    'inv.title': 'Inventory Management',
    'inv.total_items': 'Total Items',
    'inv.active': 'Active Products',
    'inv.low_stock_status': 'Low Stock',
    'inv.out_of_stock_status': 'Out of Stock',
    'inv.add_product': 'Add Product',
    'inv.search': 'Search products...',
    'inv.stock_status': 'Stock Status',
    'inv.in_stock': 'In Stock',
    'inv.low_stock': 'Low Stock',
    'inv.out_of_stock': 'Out of Stock',
    'inv.category': 'Category',
    'inv.price': 'Price',
    'inv.stock': 'Stock',
    'inv.action': 'Action',
    // Procurement
    'proc.title': 'Procurement Management',
    'proc.add_order': 'Create Order',
    'proc.supplier': 'Supplier',
    'proc.total_amount': 'Total Amount',
    'proc.order_status': 'Order Status',
    'proc.pending': 'Pending',
    'proc.approved': 'Approved',
    'proc.received': 'Received',
    'proc.invoice_po': 'Invoice (PO)',
    'proc.date_received': 'Date Received',
    'proc.ticket_code': 'Ticket Code',
    'proc.warehouse_status': 'Warehouse Status',
    'proc.awaiting_delivery': 'Awaiting Delivery',
    'proc.no_orders': 'No purchase orders in the system.',
    // POS
    'pos.title': 'Point of Sale (POS)',
    'pos.cart': 'Cart',
    'pos.checkout': 'Checkout',
    'pos.total': 'Total',
    'pos.customer': 'Customer',
    'pos.search_phone': 'Search by phone number...',
    'pos.search_btn': 'Search',
    'pos.subtotal': 'Subtotal',
    'pos.tax': 'VAT (10%)',
    'pos.total_payment': 'Total Payment',
    'pos.cash': 'Cash',
    'pos.bank_qr': 'Bank QR',
    'pos.pay': 'Pay',
    'pos.print_receipt': 'Print Invoice',
    'pos.guest': 'Walk-in Guest',
    'pos.skip': 'Skip',
    'pos.phone': 'Phone',
    'pos.not_exist': 'does not exist',
    'pos.enter_new_name': 'Enter new customer name...',
    'pos.create_and_select': '+ Create & Select',
    'pos.creating': 'Creating...',
    // Partners
    'part.title': 'Partners Management',
    'part.customers': 'Customers',
    'part.suppliers': 'Suppliers',
    // Time Management
    'time.title': 'Attendance & Leave',
    'time.check_in': 'Check In',
    'time.check_out': 'Check Out',
    'time.toast_in_success': 'Checked in successfully!',
    'time.toast_in_desc': 'Have a great and energetic shift! ✨',
    'time.toast_out_desc': 'Thank you for a wonderful workday. Rest well! 🌙',
    'time.toast_err_conn': 'Server connection error!',
    'time.leave_annual': 'Annual leave (Paid)',
    'time.leave_sick': 'Sick leave',
    'time.leave_unpaid': 'Unpaid personal leave',
    'time.date_err': 'Date error',
    'time.date_err_desc': 'End date must be greater than or equal to start date!',
    'time.submit_success': 'Request submitted successfully!',
    'time.submit_err': 'Error submitting request!',
    'time.history_title': 'Detailed Attendance History',
    'time.col_date': 'Date',
    'time.col_in': 'Check-in Time',
    'time.col_out': 'Check-out Time',
    'time.col_work': 'Work Hours',
    'time.col_ot': 'Overtime',
    'time.col_status': 'Status',
    'time.col_notes': 'Notes',
    'time.hours': 'hours',
    'time.working': 'Working',
    'time.no_attendance': 'No attendance data.',
    'time.create_leave': 'Create Leave Request',
    'time.leave_type': 'Leave Type',
    'time.from_date': 'From Date',
    'time.to_date': 'To Date',
    'time.total_days': 'Total Days',
    'time.auto_calc': '(Auto calculated)',
    'time.reason': 'Detailed Reason',
    'time.submit_leave': 'Submit Request',
    'time.submitted_leaves': 'Submitted Requests List',
    'time.leave_col_type': 'Type',
    'time.leave_col_time': 'Duration',
    'time.leave_col_days': 'Days',
    'time.days_count': 'days',
    'time.pending': 'Pending',
    'time.approved': 'Approved',
    'time.rejected': 'Rejected',
    'time.no_leaves': 'You have not submitted any leave requests.',
    // Multi-Store
    'store.title': 'Branch System',
    'store.add': 'Add Branch',
    'store.add_coming': 'Add branch feature is coming soon',
    'store.active': 'Active',
    'store.staff': 'Staff',
    'store.staff_member': 'members',
    'store.warehouse': 'Warehouses',
    'store.warehouse_location': 'locations',
    'store.details': 'Details',
    'store.manager': 'Direct Manager',
    'store.no_manager': 'No manager assigned',
    'store.contact': 'Contact Information',
    'store.recent_activities': 'Recent Activities',
    'store.sync_msg': 'Stock synchronized from Main Warehouse',
    'store.minutes_ago': '15 minutes ago',
    'store.manage_staff': 'Manage Staff',
    'store.view_layout': 'View Warehouse Layout',
    'store.recommendation': 'AI Recommendation',
    'store.recommendation_msg': 'This branch is performing 15% higher than the same period last month. Consider expanding warehouse space.',
    // Logistics
    'log.title': 'Logistics & Inventory Tickets',
    'log.err_load': 'Error loading inventory ticket data!',
    'log.err_full_info': 'Please enter all required information!',
    'log.success_transfer': 'Inventory transfer ticket created successfully!',
    'log.err_connection': 'Server connection error!',
    'log.success_approve': 'Inventory intake approved successfully! Stock added.',
    'log.err_approve': 'Error approving inventory intake!',
    'log.code': 'Ticket Code',
    'log.type': 'Ticket Type',
    'log.source': 'From (Source)',
    'log.destination': 'To (Destination)',
    'log.date': 'Date Created',
    'log.total_value': 'Total Value',
    'log.action_status': 'Action / Status',
    'log.loading': 'Loading inventory tickets...',
    'log.no_data': 'No inventory tickets available.',
    'log.confirm_intake': 'Confirm Intake',
    'log.completed': 'Completed',
    'log.confirm_intake_question': 'Are you sure the goods have been fully delivered and want to intake for this ticket? Stock counts will be updated automatically.',
    'log.cancel': 'Cancel',
    'log.processing': 'Processing...',
    'log.confirm_intake_btn': 'Confirm Intake',
    'log.create_transfer_title': 'Create Transfer Ticket',
    'log.from_warehouse': 'From Warehouse',
    'log.select_from_warehouse': 'Select source warehouse',
    'log.to_warehouse': 'To Warehouse',
    'log.select_to_warehouse': 'Select destination warehouse',
    'log.product': 'Product',
    'log.select_product': 'Select product',
    'log.stock_lbl': 'Stock',
    'log.transfer_qty': 'Transfer Qty',
    'log.system_error': 'System error',
    // Returns
    'ret.title': 'Returns & Exchanges',
    'ret.create_ticket_pos': 'Create Return Ticket (POS)',
    'ret.approve_requests': 'Approve Requests',
    'ret.lookup_invoice': 'Search Invoice',
    'ret.invoice_placeholder': 'Invoice ID (e.g., INV-1)...',
    'ret.searching': 'Searching...',
    'ret.check_btn': 'Verify',
    'ret.customer': 'Customer',
    'ret.purchase_date': 'Purchase Date',
    'ret.product': 'Product',
    'ret.qty_ratio': 'Return / Bought Qty',
    'ret.restock': 'Restock item?',
    'ret.note_to_manager': 'Note to Manager (Return Reason)',
    'ret.note_placeholder': 'e.g., Damaged seal, request refund...',
    'ret.total_refund': 'Total Refund Amount',
    'ret.submit_request': 'Submit Return Request',
    'ret.no_requests': 'No return requests found.',
    'ret.pending_msg': 'Pending Approval',
    'ret.completed_msg': 'Request Completed',
    'ret.rejected_msg': 'Request Rejected',
    'ret.reject_btn': 'Reject',
    'ret.complete_btn': 'Complete',
    'ret.amount_to_refund': 'Amount to Refund',
    'ret.success_submit': 'Return request submitted to manager!',
    'ret.success_approve': 'Approved return successfully!',
    'ret.success_reject': 'Rejected return successfully!',
    'ret.err_select_product': 'Please select products to return!',
    'ret.err_connection': 'Server connection error!',
    'ret.err_not_found': 'Invoice not found',
    'ret.reason_lbl': 'Reason',
    'ret.no_reason': 'None',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
