-- ============================================================
-- PHẦN 1: RÀNG BUỘC LIÊN THUỘC TÍNH (INTRA-RELATION CONSTRAINTS)
-- ============================================================
-- Ràng buộc kiểm tra miền giá trị hợp lệ (>= 0, định dạng email, phân loại trạng thái)

-- Bảng CHAM_CONG 
ALTER TABLE CHAM_CONG ADD CONSTRAINT CHK_CC_SOGIOLAM CHECK (SOGIOLAM >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHAM_CONG ADD CONSTRAINT CHK_CC_TANGCA CHECK (TANGCA >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_BAO_HIEM
ALTER TABLE CHI_TIET_BAO_HIEM ADD CONSTRAINT CHK_CTBH_TIEN CHECK (BHXH_NV >= 0 AND BHYT_NV >= 0 AND BHTN_NV >= 0 AND HUUTRI_DN >= 0 AND OMDAU_THAISAN_DN >= 0 AND TNLDBNN_DN >= 0 AND BHYT_DN >= 0 AND BHTN_DN >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_DOI_TRA
ALTER TABLE CHI_TIET_DOI_TRA ADD CONSTRAINT CHK_CTDT_SLTRA CHECK (SOLUONG_TRA > 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_DOI_TRA ADD CONSTRAINT CHK_CTDT_DGTRA CHECK (DONGIA_TRA >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_DOI_TRA ADD CONSTRAINT CHK_CTDT_SLDOI CHECK (SOLUONG_DOI >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_DOI_TRA ADD CONSTRAINT CHK_CTDT_DGDOI CHECK (DONGIA_DOI >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_DON_HANG
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT CHK_CTDH_SL CHECK (SOLUONG > 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT CHK_CTDH_DG CHECK (DONGIA >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT CHK_CTDH_TT CHECK (THANHTIEN >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_HOA_DON_BAN_HANG
ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG ADD CONSTRAINT CHK_CTHDBH_SL CHECK (SOLUONG > 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG ADD CONSTRAINT CHK_CTHDBH_DG CHECK (DONGIA >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG ADD CONSTRAINT CHK_CTHDBH_TT CHECK (THANHTIEN >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_HOA_DON_MUA_HANG
ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG ADD CONSTRAINT CHK_CTHDMH_SL CHECK (SOLUONG > 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG ADD CONSTRAINT CHK_CTHDMH_DG CHECK (DONGIA >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG ADD CONSTRAINT CHK_CTHDMH_TT CHECK (THANHTIEN >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG ADD CONSTRAINT CHK_CTHDMH_SLNHAN CHECK (SOLUONGDANHAN >= 0 AND SOLUONGDANHAN <= SOLUONG) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_KIEM_KE
ALTER TABLE CHI_TIET_KIEM_KE ADD CONSTRAINT CHK_CTKK_SLHT CHECK (SLHETHONG >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_KIEM_KE ADD CONSTRAINT CHK_CTKK_SLTT CHECK (SLTHUCTE >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_PHIEU
ALTER TABLE CHI_TIET_PHIEU ADD CONSTRAINT CHK_CTP_SL CHECK (SOLUONG > 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_PHIEU ADD CONSTRAINT CHK_CTP_DG CHECK (DONGIA >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_PHIEU ADD CONSTRAINT CHK_CTP_TT CHECK (THANHTIEN >= 0) ENABLE NOVALIDATE;

-- Bảng CHI_TIET_THUE_TNCN
ALTER TABLE CHI_TIET_THUE_TNCN ADD CONSTRAINT CHK_CTTNCN_BAC CHECK (BACTHUE > 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_THUE_TNCN ADD CONSTRAINT CHK_CTTNCN_THUNHAP CHECK (THUNHAPCHIUTHUE >= 0) ENABLE NOVALIDATE;
ALTER TABLE CHI_TIET_THUE_TNCN ADD CONSTRAINT CHK_CTTNCN_TIENTHUE CHECK (TIENTHUE >= 0) ENABLE NOVALIDATE;

-- Bảng DON_HANG
ALTER TABLE DON_HANG ADD CONSTRAINT CHK_DH_TONGTIEN CHECK (TONGTIENTAMTINH >= 0) ENABLE NOVALIDATE;
ALTER TABLE DON_HANG ADD CONSTRAINT CHK_DH_DIEMMD CHECK (DIEMMUONDUNG >= 0) ENABLE NOVALIDATE;

-- Bảng DON_XIN_NGHI_PHEP
ALTER TABLE DON_XIN_NGHI_PHEP ADD CONSTRAINT CHK_DXNP_SONGAY CHECK (SONGAY > 0) ENABLE NOVALIDATE;

-- Bảng GIAO_DICH_TIEN
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT CHK_GDT_SOTIEN CHECK (SOTIEN > 0) ENABLE NOVALIDATE;

-- Bảng HOA_DON_BAN_HANG
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT CHK_HDBH_TONGTIEN CHECK (TONGTIEN >= 0) ENABLE NOVALIDATE;
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT CHK_HDBH_DIEMTICH CHECK (DIEMTICHDUOC >= 0) ENABLE NOVALIDATE;
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT CHK_HDBH_DIEMSUDUNG CHECK (DIEMSUDUNG >= 0) ENABLE NOVALIDATE;

-- Bảng HOA_DON_MUA_HANG
ALTER TABLE HOA_DON_MUA_HANG ADD CONSTRAINT CHK_HDMH_TONGTIEN CHECK (TONGTIEN >= 0) ENABLE NOVALIDATE;

-- Bảng HO_SO_LUONG
ALTER TABLE HO_SO_LUONG ADD CONSTRAINT CHK_HSL_MUCLUONG CHECK (MUCLUONG >= 0) ENABLE NOVALIDATE;
ALTER TABLE HO_SO_LUONG ADD CONSTRAINT CHK_HSL_GIAMTRU CHECK (GIAMTRUBANTHAN >= 0) ENABLE NOVALIDATE;
ALTER TABLE HO_SO_LUONG ADD CONSTRAINT CHK_HSL_SNPT CHECK (SONGUOIPHUTHUOC >= 0) ENABLE NOVALIDATE;
ALTER TABLE HO_SO_LUONG ADD CONSTRAINT CHK_HSL_TGNPT CHECK (TIENGIAMNPT >= 0) ENABLE NOVALIDATE;

-- Bảng KHACH_HANG
ALTER TABLE KHACH_HANG ADD CONSTRAINT CHK_KH_DIEM CHECK (DIEMTICHLUY >= 0) ENABLE NOVALIDATE;

-- Bảng PHIEU_DOI_TRA
ALTER TABLE PHIEU_DOI_TRA ADD CONSTRAINT CHK_PDT_TTHOAN CHECK (TONGTIEN_HOAN >= 0) ENABLE NOVALIDATE;
ALTER TABLE PHIEU_DOI_TRA ADD CONSTRAINT CHK_PDT_TTTHEM CHECK (TONGTIEN_THU_THEM >= 0) ENABLE NOVALIDATE;

-- Bảng PHIEU_KHO
ALTER TABLE PHIEU_KHO ADD CONSTRAINT CHK_PK_TONGGIATRI CHECK (TONGGIATRIPHIEU >= 0) ENABLE NOVALIDATE;

-- Bảng PHIEU_LUONG
ALTER TABLE PHIEU_LUONG ADD CONSTRAINT CHK_PL_LUONG CHECK (LUONG >= 0) ENABLE NOVALIDATE;
ALTER TABLE PHIEU_LUONG ADD CONSTRAINT CHK_PL_TONGBH CHECK (TONGBAOHIEMNV >= 0) ENABLE NOVALIDATE;
ALTER TABLE PHIEU_LUONG ADD CONSTRAINT CHK_PL_TONGTHUE CHECK (TONGTHUETNCN >= 0) ENABLE NOVALIDATE;
ALTER TABLE PHIEU_LUONG ADD CONSTRAINT CHK_PL_THUCLINH CHECK (THUCLINH >= 0) ENABLE NOVALIDATE;

-- Bảng QUAN_LY_PHEP
ALTER TABLE QUAN_LY_PHEP ADD CONSTRAINT CHK_QLP_NAM CHECK (NAM > 0) ENABLE NOVALIDATE;
ALTER TABLE QUAN_LY_PHEP ADD CONSTRAINT CHK_QLP_TONGPHEP CHECK (TONGPHEP >= 0) ENABLE NOVALIDATE;
ALTER TABLE QUAN_LY_PHEP ADD CONSTRAINT CHK_QLP_DADUNG CHECK (DADUNG >= 0 AND DADUNG <= TONGPHEP) ENABLE NOVALIDATE;
ALTER TABLE QUAN_LY_PHEP ADD CONSTRAINT CHK_QLP_CONLAI CHECK (CONLAI >= 0) ENABLE NOVALIDATE;

-- Bảng QUYET_TOAN_THUE_BH
ALTER TABLE QUYET_TOAN_THUE_BH ADD CONSTRAINT CHK_QTTBH_TIEN CHECK (THUETNCN_NOPHO >= 0 AND BHBB_NV >= 0 AND BHBB_DV >= 0 AND TONGNOPNSNN >= 0) ENABLE NOVALIDATE;

-- Bảng SAN_PHAM
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_GIA CHECK (GIANIEMYET >= 0) ENABLE NOVALIDATE;
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_THUE CHECK (THUE >= 0) ENABLE NOVALIDATE;
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_COTHEMUA CHECK (COTHEMUA IN (0, 1)) ENABLE NOVALIDATE;
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_COTHEBAN CHECK (COTHEBAN IN (0, 1)) ENABLE NOVALIDATE;
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_POS CHECK (POS IN (0, 1)) ENABLE NOVALIDATE;

-- Bảng TAI_KHOAN
ALTER TABLE TAI_KHOAN ADD CONSTRAINT CHK_TK_SODU CHECK (SODUHIENTAI >= 0) ENABLE NOVALIDATE;

-- Bảng TAI_KHOAN_NHAN_VIEN
ALTER TABLE TAI_KHOAN_NHAN_VIEN ADD CONSTRAINT CHK_TKNV_TRANGTHAI CHECK (TRANG_THAI IN (0, 1)) ENABLE NOVALIDATE;

-- Bảng TON_KHO
ALTER TABLE TON_KHO ADD CONSTRAINT CHK_TKHO_SLTON CHECK (SOLUONGTON >= 0) ENABLE NOVALIDATE;

-- Định dạng Email
ALTER TABLE NHANVIEN ADD CONSTRAINT CHK_NV_EMAIL CHECK (EMAIL LIKE '%@%') ENABLE NOVALIDATE;
ALTER TABLE DOI_TAC ADD CONSTRAINT CHK_DT_EMAIL CHECK (EMAIL IS NULL OR EMAIL LIKE '%@%') ENABLE NOVALIDATE;



-- ============================================================
-- PHẦN 2: RÀNG BUỘC LIÊN BỘ (INTER-TUPLE CONSTRAINTS) 
-- ============================================================
-- Ràng buộc Unique đối với những dữ liệu phải là duy nhất trên toàn bảng
-- Lưu ý: Ràng buộc UNIQUE không hỗ trợ ENABLE NOVALIDATE trực tiếp theo cách thông thường nếu index bị vi phạm. Nhưng để an toàn cú pháp, cứ áp dụng nếu bảng chưa có lỗi trùng lặp.

-- Bảng NHANVIEN: Email và Số điện thoại phải là duy nhất
ALTER TABLE NHANVIEN ADD CONSTRAINT UQ_NV_EMAIL UNIQUE (EMAIL) ENABLE NOVALIDATE;
ALTER TABLE NHANVIEN ADD CONSTRAINT UQ_NV_SDT UNIQUE (SDT) ENABLE NOVALIDATE;

-- Bảng SAN_PHAM: Mã vạch sản phẩm là duy nhất
ALTER TABLE SAN_PHAM ADD CONSTRAINT UQ_SP_MAVACH UNIQUE (MAVACH) ENABLE NOVALIDATE;

-- Bảng CUA_HANG: Số điện thoại là duy nhất
ALTER TABLE CUA_HANG ADD CONSTRAINT UQ_CH_SDT UNIQUE (SODIENTHOAI) ENABLE NOVALIDATE;

-- Bảng DOI_TAC: Số điện thoại và Email là duy nhất
ALTER TABLE DOI_TAC ADD CONSTRAINT UQ_DT_SDT UNIQUE (SODIENTHOAI) ENABLE NOVALIDATE;
ALTER TABLE DOI_TAC ADD CONSTRAINT UQ_DT_EMAIL UNIQUE (EMAIL) ENABLE NOVALIDATE;

-- Bảng TAI_KHOAN_NHAN_VIEN: Username phải là duy nhất
ALTER TABLE TAI_KHOAN_NHAN_VIEN ADD CONSTRAINT UQ_TKNV_USERNAME UNIQUE (USERNAME) ENABLE NOVALIDATE;

-- Bảng TAI_KHOAN: Số tài khoản là duy nhất (nếu có)
ALTER TABLE TAI_KHOAN ADD CONSTRAINT UQ_TK_STK UNIQUE (SOTAIKHOAN) ENABLE NOVALIDATE;


-- ============================================================
-- PHẦN 3: RÀNG BUỘC DO BỐI CẢNH THỜI GIAN VÀ CHU TRÌNH (BẰNG ADD CONSTRAINT)
-- ============================================================
-- Các ràng buộc được thực hiện bằng cách so sánh 2 cột thời gian trên cùng 1 bảng

-- 3.1: Bảng CHAM_CONG - Giờ ra phải sau giờ vào
ALTER TABLE CHAM_CONG ADD CONSTRAINT CHK_CC_THOIGIAN CHECK (GIORA > GIOVAO) ENABLE NOVALIDATE;

-- 3.2: Bảng DON_XIN_NGHI_PHEP - Ngày kết thúc nghỉ phải sau hoặc bằng ngày bắt đầu
ALTER TABLE DON_XIN_NGHI_PHEP ADD CONSTRAINT CHK_DXNP_NGAY CHECK (TUNGAY <= DENNGAY) ENABLE NOVALIDATE;

-- 3.3: Bảng PHIEU_DOI_TRA - Ngày duyệt phiếu đổi trả không được trước ngày tạo
ALTER TABLE PHIEU_DOI_TRA ADD CONSTRAINT CHK_PDT_NGAYDUYET CHECK (NGAYDUYET IS NULL OR NGAYDUYET >= NGAYTAO) ENABLE NOVALIDATE;

-- 3.4: Bảng PHIEU_KHO - Ngày thực tế nhập/xuất kho không được trước ngày lập phiếu
ALTER TABLE PHIEU_KHO ADD CONSTRAINT CHK_PK_NGAYTHUCPHE CHECK (NGAYTHUCPHE >= NGAYLAP) ENABLE NOVALIDATE;