-- ============================================================
-- TỔNG HỢP TRIGGERS (48 Items)
-- ============================================================

-- 1. TRG_AUDIT_HS_LUONG
CREATE OR REPLACE TRIGGER TRG_AUDIT_HS_LUONG
BEFORE UPDATE ON HO_SO_LUONG
FOR EACH ROW
BEGIN
    :NEW.NGAYCAPNHAP := SYSDATE;
END;
/

-- 2. TRG_AUDIT_PASS_HISTORY
CREATE OR REPLACE TRIGGER TRG_AUDIT_PASS_HISTORY
BEFORE UPDATE OF PASSWORDHASH ON TAI_KHOAN_NHAN_VIEN
FOR EACH ROW
BEGIN
    :NEW.PASSWORDHASHHISTORY := :OLD.PASSWORDHASH || ';' || NVL(:OLD.PASSWORDHASHHISTORY, '');
END;
/

-- 3. TRG_AUDIT_TON_KHO
CREATE OR REPLACE TRIGGER TRG_AUDIT_TON_KHO
BEFORE UPDATE ON TON_KHO
FOR EACH ROW
BEGIN
    :NEW.NGAYCAPNHAP := SYSTIMESTAMP;
END;
/

-- 4. TRG_AUTO_UPRANK_KHACHHANG
CREATE OR REPLACE TRIGGER TRG_AUTO_UPRANK_KHACHHANG
BEFORE UPDATE OF DIEMTICHLUY ON KHACH_HANG
FOR EACH ROW
BEGIN
    :NEW.LOAIKHACHHANG := FUNC_TINH_HANG_THE(:NEW.DIEMTICHLUY);
END;
/

-- 5. TRG_CALC_CHENHLECH_DT
CREATE OR REPLACE TRIGGER TRG_CALC_CHENHLECH_DT
BEFORE INSERT OR UPDATE ON CHI_TIET_DOI_TRA
FOR EACH ROW
BEGIN
    :NEW.GIATRI_CHENH_LECH := NVL(:NEW.SOLUONG_DOI * :NEW.DONGIA_DOI, 0) - NVL(:NEW.SOLUONG_TRA * :NEW.DONGIA_TRA, 0);
END;
/

-- 6. TRG_CALC_CT_DONHANG
CREATE OR REPLACE TRIGGER TRG_CALC_CT_DONHANG
BEFORE INSERT OR UPDATE ON CHI_TIET_DON_HANG
FOR EACH ROW
BEGIN
    :NEW.THANHTIEN := NVL(:NEW.SOLUONG, 0) * NVL(:NEW.DONGIA, 0);
END;
/

-- 7. TRG_CALC_CT_HDBANHANG
CREATE OR REPLACE TRIGGER TRG_CALC_CT_HDBANHANG
BEFORE INSERT OR UPDATE ON CHI_TIET_HOA_DON_BAN_HANG
FOR EACH ROW
BEGIN
    :NEW.THANHTIEN := NVL(:NEW.SOLUONG, 0) * NVL(:NEW.DONGIA, 0);
END;
/

-- 8. TRG_CALC_CT_HDMUAHANG
CREATE OR REPLACE TRIGGER TRG_CALC_CT_HDMUAHANG
BEFORE INSERT OR UPDATE ON CHI_TIET_HOA_DON_MUA_HANG
FOR EACH ROW
BEGIN
    :NEW.THANHTIEN := NVL(:NEW.SOLUONG, 0) * NVL(:NEW.DONGIA, 0);
END;
/

-- 9. TRG_CALC_CT_PHIEUKHO
CREATE OR REPLACE TRIGGER TRG_CALC_CT_PHIEUKHO
BEFORE INSERT OR UPDATE ON CHI_TIET_PHIEU
FOR EACH ROW
BEGIN
    :NEW.THANHTIEN := NVL(:NEW.SOLUONG, 0) * NVL(:NEW.DONGIA, 0);
END;
/

-- 10. TRG_CALC_GIAMTRU_NPT
CREATE OR REPLACE TRIGGER TRG_CALC_GIAMTRU_NPT
BEFORE INSERT OR UPDATE ON HO_SO_LUONG
FOR EACH ROW
BEGIN
    :NEW.TIENGIAMNPT := NVL(:NEW.SONGUOIPHUTHUOC, 0) * 4400000;
END;
/

-- 11. TRG_CALC_SLLECH_KIEMKE
CREATE OR REPLACE TRIGGER TRG_CALC_SLLECH_KIEMKE
BEFORE INSERT OR UPDATE ON CHI_TIET_KIEM_KE
FOR EACH ROW
BEGIN
    :NEW.SLLECH := NVL(:NEW.SLTHUCTE, 0) - NVL(:NEW.SLHETHONG, 0);
END;
/

-- 12. TRG_CALC_SONGAY_NGHI
CREATE OR REPLACE TRIGGER TRG_CALC_SONGAY_NGHI
BEFORE INSERT OR UPDATE ON DON_XIN_NGHI_PHEP
FOR EACH ROW
BEGIN
    :NEW.SONGAY := TRUNC(:NEW.DENNGAY) - TRUNC(:NEW.TUNGAY) + 1;
END;
/

-- 13. TRG_CALC_THUCLINH
CREATE OR REPLACE TRIGGER TRG_CALC_THUCLINH
BEFORE INSERT OR UPDATE ON PHIEU_LUONG
FOR EACH ROW
BEGIN
    :NEW.THUCLINH := NVL(:NEW.LUONG, 0) - NVL(:NEW.TONGBAOHIEMNV, 0) - NVL(:NEW.TONGTHUETNCN, 0);
END;
/

-- 14. TRG_DEDUCT_LEAVE_DAYS
CREATE OR REPLACE TRIGGER TRG_DEDUCT_LEAVE_DAYS
AFTER UPDATE OF TRANGTHAI ON DON_XIN_NGHI_PHEP
FOR EACH ROW
WHEN (NEW.TRANGTHAI = 'Đã duyệt' AND OLD.TRANGTHAI != 'Đã duyệt')
BEGIN
    UPDATE QUAN_LY_PHEP 
    SET DADUNG = DADUNG + :NEW.SONGAY,
        CONLAI = CONLAI - :NEW.SONGAY
    WHERE MANHANVIEN = :NEW.MANHANVIEN 
    AND NAM = EXTRACT(YEAR FROM :NEW.TUNGAY);
END;
/

-- 15. TRG_SET_DEFAULT_DATES_TKNV
CREATE OR REPLACE TRIGGER TRG_SET_DEFAULT_DATES_TKNV
BEFORE INSERT ON TAI_KHOAN_NHAN_VIEN
FOR EACH ROW
BEGIN
    :NEW.NGAYTAO := SYSDATE;
    :NEW.LAST_LOGIN := SYSTIMESTAMP;
END;
/

-- 16. TRG_SUM_DONHANG
CREATE OR REPLACE TRIGGER TRG_SUM_DONHANG
AFTER INSERT OR UPDATE OR DELETE ON CHI_TIET_DON_HANG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE DON_HANG SET TONGTIENTAMTINH = NVL(TONGTIENTAMTINH, 0) + :NEW.THANHTIEN WHERE MADONHANG = :NEW.MADONHANG;
    ELSIF UPDATING THEN
        UPDATE DON_HANG SET TONGTIENTAMTINH = NVL(TONGTIENTAMTINH, 0) - :OLD.THANHTIEN + :NEW.THANHTIEN WHERE MADONHANG = :NEW.MADONHANG;
    ELSIF DELETING THEN
        UPDATE DON_HANG SET TONGTIENTAMTINH = NVL(TONGTIENTAMTINH, 0) - :OLD.THANHTIEN WHERE MADONHANG = :OLD.MADONHANG;
    END IF;
END;
/

-- 17. TRG_SUM_HDBANHANG
CREATE OR REPLACE TRIGGER TRG_SUM_HDBANHANG
AFTER INSERT OR UPDATE OR DELETE ON CHI_TIET_HOA_DON_BAN_HANG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE HOA_DON_BAN_HANG SET TONGTIEN = NVL(TONGTIEN, 0) + :NEW.THANHTIEN WHERE MAHOADON = :NEW.MAHOADON;
    ELSIF UPDATING THEN
        UPDATE HOA_DON_BAN_HANG SET TONGTIEN = NVL(TONGTIEN, 0) - :OLD.THANHTIEN + :NEW.THANHTIEN WHERE MAHOADON = :NEW.MAHOADON;
    ELSIF DELETING THEN
        UPDATE HOA_DON_BAN_HANG SET TONGTIEN = NVL(TONGTIEN, 0) - :OLD.THANHTIEN WHERE MAHOADON = :OLD.MAHOADON;
    END IF;
END;
/

-- 18. TRG_SUM_HDMUAHANG
CREATE OR REPLACE TRIGGER TRG_SUM_HDMUAHANG
AFTER INSERT OR UPDATE OR DELETE ON CHI_TIET_HOA_DON_MUA_HANG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE HOA_DON_MUA_HANG SET TONGTIEN = NVL(TONGTIEN, 0) + :NEW.THANHTIEN WHERE MAHOADONMUA = :NEW.MAHOADONMUA;
    ELSIF UPDATING THEN
        UPDATE HOA_DON_MUA_HANG SET TONGTIEN = NVL(TONGTIEN, 0) - :OLD.THANHTIEN + :NEW.THANHTIEN WHERE MAHOADONMUA = :NEW.MAHOADONMUA;
    ELSIF DELETING THEN
        UPDATE HOA_DON_MUA_HANG SET TONGTIEN = NVL(TONGTIEN, 0) - :OLD.THANHTIEN WHERE MAHOADONMUA = :OLD.MAHOADONMUA;
    END IF;
END;
/

-- 19. TRG_SUM_PHIEUKHO
CREATE OR REPLACE TRIGGER TRG_SUM_PHIEUKHO
AFTER INSERT OR UPDATE OR DELETE ON CHI_TIET_PHIEU
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE PHIEU_KHO SET TONGGIATRIPHIEU = NVL(TONGGIATRIPHIEU, 0) + :NEW.THANHTIEN WHERE SOPHIEU = :NEW.SOPHIEU;
    ELSIF UPDATING THEN
        UPDATE PHIEU_KHO SET TONGGIATRIPHIEU = NVL(TONGGIATRIPHIEU, 0) - :OLD.THANHTIEN + :NEW.THANHTIEN WHERE SOPHIEU = :NEW.SOPHIEU;
    ELSIF DELETING THEN
        UPDATE PHIEU_KHO SET TONGGIATRIPHIEU = NVL(TONGGIATRIPHIEU, 0) - :OLD.THANHTIEN WHERE SOPHIEU = :OLD.SOPHIEU;
    END IF;
END;
/

-- 20. TRG_SYNC_STOCK_RETURN
CREATE OR REPLACE TRIGGER TRG_SYNC_STOCK_RETURN
AFTER INSERT ON CHI_TIET_DOI_TRA
FOR EACH ROW
DECLARE
    v_makho NUMBER;
BEGIN
    SELECT K.MAKHO INTO v_makho 
    FROM PHIEU_DOI_TRA P 
    JOIN KHO K ON P.MACUAHANG = K.MACUAHANG 
    WHERE P.MAPHIEU = :NEW.MAPHIEU 
    AND ROWNUM = 1;
    UPDATE TON_KHO SET SOLUONGTON = SOLUONGTON + :NEW.SOLUONG_TRA 
    WHERE MASANPHAM = :NEW.MASANPHAM_TRA AND MAKHO = v_makho;
    IF :NEW.MASANPHAM_DOI IS NOT NULL THEN
        UPDATE TON_KHO SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG_DOI 
        WHERE MASANPHAM = :NEW.MASANPHAM_DOI AND MAKHO = v_makho;
    END IF;
END;
/

-- 21. TRG_SYNC_STOCK_SALE
CREATE OR REPLACE TRIGGER TRG_SYNC_STOCK_SALE
AFTER INSERT ON CHI_TIET_HOA_DON_BAN_HANG
FOR EACH ROW
DECLARE
    v_makho NUMBER;
BEGIN
    SELECT K.MAKHO INTO v_makho 
    FROM HOA_DON_BAN_HANG H 
    JOIN KHO K ON H.MACUAHANG = K.MACUAHANG 
    WHERE H.MAHOADON = :NEW.MAHOADON 
    AND ROWNUM = 1;
    UPDATE TON_KHO 
    SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG,
        NGAYCAPNHAP = SYSTIMESTAMP
    WHERE MASANPHAM = :NEW.MASANPHAM 
    AND MAKHO = v_makho;
END;
/

-- 22. TRG_UPDATE_BANK_BALANCE
CREATE OR REPLACE TRIGGER TRG_UPDATE_BANK_BALANCE
AFTER INSERT ON GIAO_DICH_TIEN
FOR EACH ROW
BEGIN
    IF UPPER(:NEW.LOAIGIAODICH) = 'THU' THEN
        UPDATE TAI_KHOAN SET SODUHIENTAI = SODUHIENTAI + :NEW.SOTIEN WHERE MATAIKHOAN = :NEW.MATAIKHOAN;
    ELSIF UPPER(:NEW.LOAIGIAODICH) = 'CHI' THEN
        UPDATE TAI_KHOAN SET SODUHIENTAI = SODUHIENTAI - :NEW.SOTIEN WHERE MATAIKHOAN = :NEW.MATAIKHOAN;
    END IF;
END;
/

-- 23. TRG_UPDATE_LOYALTY_PTS
CREATE OR REPLACE TRIGGER TRG_UPDATE_LOYALTY_PTS
AFTER INSERT OR UPDATE ON HOA_DON_BAN_HANG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE KHACH_HANG 
        SET DIEMTICHLUY = NVL(DIEMTICHLUY, 0) + NVL(:NEW.DIEMTICHDUOC, 0) - NVL(:NEW.DIEMSUDUNG, 0)
        WHERE MADOITAC = :NEW.MADOITAC;
    ELSIF UPDATING THEN
        UPDATE KHACH_HANG 
        SET DIEMTICHLUY = NVL(DIEMTICHLUY, 0) 
                          - NVL(:OLD.DIEMTICHDUOC, 0) + NVL(:OLD.DIEMSUDUNG, 0)
                          + NVL(:NEW.DIEMTICHDUOC, 0) - NVL(:NEW.DIEMSUDUNG, 0)
        WHERE MADOITAC = :NEW.MADOITAC;
    END IF;
END;
/

-- 24. TRG_CHECK_STOCK_BEFORE_SALE
CREATE OR REPLACE TRIGGER TRG_CHECK_STOCK_BEFORE_SALE 
BEFORE INSERT ON CHI_TIET_DON_HANG 
FOR EACH ROW 
DECLARE
    v_tonkho NUMBER;
    v_makho NUMBER;
BEGIN 
    SELECT K.MAKHO INTO v_makho 
    FROM DON_HANG D 
    JOIN KHO K ON D.MACUAHANG = K.MACUAHANG 
    WHERE D.MADONHANG = :NEW.MADONHANG AND ROWNUM = 1;
    
    SELECT SOLUONGTON INTO v_tonkho 
    FROM TON_KHO 
    WHERE MASANPHAM = :NEW.MASANPHAM AND MAKHO = v_makho;
    
    IF v_tonkho < :NEW.SOLUONG THEN 
        RAISE_APPLICATION_ERROR(-20005, 'Hàng tồn không đủ để bán!'); 
    END IF;
END; 
/

-- 25. TRG_SYNC_STOCK_PURCHASE
CREATE OR REPLACE TRIGGER TRG_SYNC_STOCK_PURCHASE 
AFTER INSERT ON CHI_TIET_PHIEU 
FOR EACH ROW 
DECLARE
    v_loaiphieu NVARCHAR2(100);
    v_khoden NUMBER;
BEGIN 
    SELECT LOAIPHIEU, KHODEN INTO v_loaiphieu, v_khoden 
    FROM PHIEU_KHO WHERE SOPHIEU = :NEW.SOPHIEU;
    
    IF UPPER(v_loaiphieu) LIKE '%NHẬP%' AND v_khoden IS NOT NULL THEN
        MERGE INTO TON_KHO TK 
        USING (SELECT :NEW.MASANPHAM AS SP, v_khoden AS KHO FROM DUAL) src
        ON (TK.MASANPHAM = src.SP AND TK.MAKHO = src.KHO)
        WHEN MATCHED THEN 
            UPDATE SET SOLUONGTON = SOLUONGTON + :NEW.SOLUONG
        WHEN NOT MATCHED THEN 
            INSERT (MASANPHAM, MAKHO, SOLUONGTON, NGAYCAPNHAP) 
            VALUES (:NEW.MASANPHAM, v_khoden, :NEW.SOLUONG, SYSTIMESTAMP);
    END IF;
END; 
/

-- 26. TRG_PREVENT_DUPLICATE_TIMESHEET
CREATE OR REPLACE TRIGGER TRG_PREVENT_DUPLICATE_TIMESHEET 
BEFORE INSERT ON CHAM_CONG 
FOR EACH ROW 
DECLARE
    v_count NUMBER;
BEGIN 
    SELECT COUNT(*) INTO v_count 
    FROM CHAM_CONG 
    WHERE MANHANVIEN = :NEW.MANHANVIEN 
      AND TRUNC(NGAY) = TRUNC(:NEW.NGAY);
      
    IF v_count > 0 THEN 
        RAISE_APPLICATION_ERROR(-20007, 'Đã chấm công hôm nay rồi!'); 
    END IF;
END; 
/

-- 27. TRG_PREVENT_EXPIRED_STOCK_OUT
CREATE OR REPLACE TRIGGER TRG_PREVENT_EXPIRED_STOCK_OUT 
BEFORE INSERT ON CHI_TIET_PHIEU 
FOR EACH ROW 
DECLARE
    v_loaiphieu NVARCHAR2(100);
BEGIN 
    SELECT LOAIPHIEU INTO v_loaiphieu FROM PHIEU_KHO WHERE SOPHIEU = :NEW.SOPHIEU;
    
    IF UPPER(v_loaiphieu) LIKE '%XUẤT%' AND :NEW.HANSUDUNG IS NOT NULL AND :NEW.HANSUDUNG < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20008, 'Sản phẩm đã hết hạn sử dụng!');
    END IF;
END; 
/

-- 28. TRG_PREVENT_NEGATIVE_BALANCE
CREATE OR REPLACE TRIGGER TRG_PREVENT_NEGATIVE_BALANCE 
BEFORE UPDATE ON TAI_KHOAN 
FOR EACH ROW 
BEGIN 
    IF :NEW.SODUHIENTAI < 0 THEN
        RAISE_APPLICATION_ERROR(-20009, 'Số dư tài khoản không được phép âm!');
    END IF;
END; 
/

-- 29. TRG_VALIDATE_DIEM_KHACH_HANG
CREATE OR REPLACE TRIGGER TRG_VALIDATE_DIEM_KHACH_HANG 
BEFORE INSERT ON DON_HANG 
FOR EACH ROW 
DECLARE
    v_diem NUMBER;
BEGIN 
    IF :NEW.DIEMMUONDUNG > 0 THEN
        SELECT DIEMTICHLUY INTO v_diem FROM KHACH_HANG WHERE MADOITAC = :NEW.MADOITAC;
        IF v_diem < :NEW.DIEMMUONDUNG THEN
            RAISE_APPLICATION_ERROR(-20010, 'Không đủ điểm tích lũy để sử dụng!');
        END IF;
    END IF;
END; 
/

-- 30. TRG_LOCK_HOADON_DATHANHTOAN
CREATE OR REPLACE TRIGGER TRG_LOCK_HOADON_DATHANHTOAN 
BEFORE UPDATE ON CHI_TIET_HOA_DON_BAN_HANG 
FOR EACH ROW 
DECLARE
    v_count NUMBER;
BEGIN 
    SELECT COUNT(*) INTO v_count FROM HOA_DON_BAN_HANG WHERE MAHOADON = :NEW.MAHOADON;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Hóa đơn đã chốt, không thể sửa chi tiết!');
    END IF;
END; 
/

-- 31. TRG_PREVENT_DEL_CHAMCONG_CU
CREATE OR REPLACE TRIGGER TRG_PREVENT_DEL_CHAMCONG_CU 
BEFORE DELETE ON CHAM_CONG 
FOR EACH ROW 
BEGIN 
    IF EXTRACT(MONTH FROM :OLD.NGAY) < EXTRACT(MONTH FROM SYSDATE) AND EXTRACT(YEAR FROM :OLD.NGAY) <= EXTRACT(YEAR FROM SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20012, 'Không được xóa dữ liệu chấm công của kỳ trước!');
    END IF;
END; 
/

-- 32. TRG_AUTO_CREATE_TKNV
CREATE OR REPLACE TRIGGER TRG_AUTO_CREATE_TKNV 
AFTER INSERT ON NHANVIEN 
FOR EACH ROW 
BEGIN 
    INSERT INTO TAI_KHOAN_NHAN_VIEN (
        MANHANVIEN, USERNAME, PASSWORDHASH, PASSWORDHASHHISTORY, NGAYTAO, LAST_LOGIN, TRANG_THAI
    ) VALUES (
        :NEW.MANHANVIEN, 'user_' || :NEW.MANHANVIEN, 'default', '', SYSDATE, SYSTIMESTAMP, 1
    );
END; 
/

-- 33. TRG_CHECK_NCC_VALID
CREATE OR REPLACE TRIGGER TRG_CHECK_NCC_VALID 
BEFORE INSERT ON HOA_DON_MUA_HANG 
FOR EACH ROW 
DECLARE
    v_loai NVARCHAR2(100);
BEGIN 
    SELECT LOAIDOITAC INTO v_loai FROM DOI_TAC WHERE MADOITAC = :NEW.MADOITAC;
    IF v_loai != 'Nhà cung cấp' THEN
        RAISE_APPLICATION_ERROR(-20013, 'Chỉ đối tác "Nhà cung cấp" mới được lập hóa đơn mua hàng!');
    END IF;
END; 
/

-- 34. TRG_VALIDATE_MAT_KHAU_CU
CREATE OR REPLACE TRIGGER TRG_VALIDATE_MAT_KHAU_CU 
BEFORE UPDATE ON TAI_KHOAN_NHAN_VIEN 
FOR EACH ROW 
BEGIN 
    IF INSTR(:OLD.PASSWORDHASHHISTORY, :NEW.PASSWORDHASH) > 0 THEN
        RAISE_APPLICATION_ERROR(-20014, 'Mật khẩu mới không được trùng mật khẩu cũ!');
    END IF;
END; 
/

-- 35. TRG_UPDATE_SL_DA_NHAN_HDMH
CREATE OR REPLACE TRIGGER TRG_UPDATE_SL_DA_NHAN_HDMH 
AFTER INSERT ON CHI_TIET_PHIEU 
FOR EACH ROW 
DECLARE
    v_mahoadon NUMBER;
BEGIN 
    -- Bọc trong khối exception để tránh lỗi NO_DATA_FOUND nếu phiếu này không phải là nhập kho mua hàng
    BEGIN
        SELECT MAHOADON INTO v_mahoadon FROM PHIEU_KHO WHERE SOPHIEU = :NEW.SOPHIEU AND LOAIPHIEU LIKE '%mua hàng%';
        IF v_mahoadon IS NOT NULL THEN
            UPDATE CHI_TIET_HOA_DON_MUA_HANG 
            SET SOLUONGDANHAN = NVL(SOLUONGDANHAN,0) + :NEW.SOLUONG 
            WHERE MAHOADONMUA = v_mahoadon AND MASANPHAM = :NEW.MASANPHAM;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL; -- Nếu không phải phiếu mua hàng thì bỏ qua
    END;
END; 
/

-- 36. TRG_CHECK_KHO_HOP_LE_KHI_KIEM_KE
CREATE OR REPLACE TRIGGER TRG_CHECK_KHO_HOP_LE_KHI_KIEM_KE 
BEFORE INSERT ON KIEM_KE 
FOR EACH ROW 
DECLARE
    v_cuahang NUMBER;
BEGIN 
    SELECT MACUAHANG INTO v_cuahang FROM KHO WHERE MAKHO = :NEW.MAKHO;
    IF v_cuahang != :NEW.MACUAHANG THEN
        RAISE_APPLICATION_ERROR(-20015, 'Kho này không thuộc Cửa hàng đang kiểm kê!');
    END IF;
END; 
/

-- 37. TRG_RESTRICT_PHEP_AM
CREATE OR REPLACE TRIGGER TRG_RESTRICT_PHEP_AM 
BEFORE UPDATE ON QUAN_LY_PHEP 
FOR EACH ROW 
BEGIN 
    IF :NEW.CONLAI < 0 THEN
        RAISE_APPLICATION_ERROR(-20016, 'Đã dùng hết ngày phép năm!');
    END IF;
END; 
/

-- 38. TRG_AUTO_GEN_SOPHIEU_KHO
CREATE OR REPLACE TRIGGER TRG_AUTO_GEN_SOPHIEU_KHO 
BEFORE INSERT ON PHIEU_KHO 
FOR EACH ROW 
BEGIN 
    IF :NEW.SOPHIEU IS NULL THEN
        :NEW.SOPHIEU := 'PK-' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISS');
    END IF;
END; 
/

-- 39. TRG_PREVENT_XOA_NHAN_VIEN
CREATE OR REPLACE TRIGGER TRG_PREVENT_XOA_NHAN_VIEN
BEFORE DELETE ON NHANVIEN
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20017, 'Tuyệt đối không được xóa nhân viên, chỉ được vô hiệu hóa!');
END;
/

-- 40. TRG_CHECK_GIO_LAM_HOP_LE
CREATE OR REPLACE TRIGGER TRG_CHECK_GIO_LAM_HOP_LE
BEFORE INSERT OR UPDATE ON CHAM_CONG
FOR EACH ROW
BEGIN
    IF :NEW.SOGIOLAM + NVL(:NEW.TANGCA, 0) > 24 THEN
        RAISE_APPLICATION_ERROR(-20018, 'Tổng số giờ làm trong ngày không thể vượt quá 24h!');
    END IF;
END;
/

-- 41. TRG_CHONG_BAN_HANG_DOI_TAC_KHOA
CREATE OR REPLACE TRIGGER TRG_CHONG_BAN_HANG_DOI_TAC_KHOA
BEFORE INSERT ON HOA_DON_BAN_HANG
FOR EACH ROW
DECLARE 
    v_loai NVARCHAR2(100);
BEGIN
    SELECT LOAIDOITAC INTO v_loai FROM DOI_TAC WHERE MADOITAC = :NEW.MADOITAC;
    IF v_loai = 'Bị khóa' THEN 
        RAISE_APPLICATION_ERROR(-20019, 'Đối tác đang bị khóa!'); 
    END IF;
END;
/

-- 42. TRG_BAT_LOI_KHO_DI_KHO_DEN
CREATE OR REPLACE TRIGGER TRG_BAT_LOI_KHO_DI_KHO_DEN
BEFORE INSERT ON PHIEU_KHO
FOR EACH ROW
BEGIN
    IF :NEW.KHODI IS NOT NULL AND :NEW.KHODEN IS NOT NULL AND :NEW.KHODI = :NEW.KHODEN THEN
        RAISE_APPLICATION_ERROR(-20020, 'Kho đi và Kho đến không được giống nhau!');
    END IF;
END;
/

-- 43. TRG_CHONG_PHIEU_KHO_RONG
CREATE OR REPLACE TRIGGER TRG_CHONG_PHIEU_KHO_RONG
AFTER UPDATE OF TRANGTHAI ON PHIEU_KHO
FOR EACH ROW
DECLARE 
    v_c NUMBER;
BEGIN
    IF :NEW.TRANGTHAI = 'Đã chốt' THEN
        SELECT COUNT(*) INTO v_c FROM CHI_TIET_PHIEU WHERE SOPHIEU = :NEW.SOPHIEU;
        IF v_c = 0 THEN 
            RAISE_APPLICATION_ERROR(-20021, 'Phiếu kho không có chi tiết hàng hóa!'); 
        END IF;
    END IF;
END;
/

-- 44. TRG_VALIDATE_FORMAT_SDT
CREATE OR REPLACE TRIGGER TRG_VALIDATE_FORMAT_SDT
BEFORE INSERT OR UPDATE ON NHANVIEN
FOR EACH ROW
BEGIN
    :NEW.SDT := REGEXP_REPLACE(:NEW.SDT, '[^0-9]', '');
    IF LENGTH(:NEW.SDT) < 10 THEN 
        RAISE_APPLICATION_ERROR(-20022, 'SĐT không hợp lệ!'); 
    END IF;
END;
/

-- 45. TRG_KHONG_XOA_DANH_MUC_CO_SAN_PHAM
CREATE OR REPLACE TRIGGER TRG_KHONG_XOA_DANH_MUC_CO_SAN_PHAM
BEFORE DELETE ON DANH_MUC
FOR EACH ROW
DECLARE 
    v_c NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_c FROM SAN_PHAM_DANH_MUC WHERE MADANHMUC = :OLD.MADANHMUC;
    IF v_c > 0 THEN 
        RAISE_APPLICATION_ERROR(-20023, 'Danh mục đang có sản phẩm, không thể xóa!'); 
    END IF;
END;
/

-- 46. TRG_CHECK_GIA_BAN_THAP_HON_NHAP
CREATE OR REPLACE TRIGGER TRG_CHECK_GIA_BAN_THAP_HON_NHAP
BEFORE UPDATE OF GIANIEMYET ON SAN_PHAM
FOR EACH ROW
DECLARE 
    v_gianhap NUMBER;
BEGIN
    SELECT NVL(AVG(DONGIA),0) INTO v_gianhap 
    FROM CHI_TIET_HOA_DON_MUA_HANG 
    WHERE MASANPHAM = :NEW.MASANPHAM;
    
    IF :NEW.GIANIEMYET < v_gianhap AND v_gianhap > 0 THEN
        RAISE_APPLICATION_ERROR(-20024, 'Cập nhật giá bán thấp hơn giá vốn!');
    END IF;
END;
/

-- 47. TRG_CHONG_SUA_GIAO_DICH_TIEN
CREATE OR REPLACE TRIGGER TRG_CHONG_SUA_GIAO_DICH_TIEN
BEFORE UPDATE OR DELETE ON GIAO_DICH_TIEN
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20025, 'CẢNH BÁO: Không được sửa dữ liệu sổ quỹ tiền mặt!');
END;
/

-- 48. TRG_AUTO_UPPERCASE_NAME
CREATE OR REPLACE TRIGGER TRG_AUTO_UPPERCASE_NAME
BEFORE INSERT OR UPDATE ON NHANVIEN
FOR EACH ROW
BEGIN
    :NEW.HOTEN := INITCAP(TRIM(:NEW.HOTEN));
    :NEW.EMAIL := LOWER(TRIM(:NEW.EMAIL));
END;
/

