-- ============================================================
-- PHẦN 1: TẠO BẢNG
-- ============================================================

CREATE TABLE CHAM_CONG (
    MACHAMCONG NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAY DATE NOT NULL,
    GIOVAO TIMESTAMP(6) NOT NULL,
    GIORA TIMESTAMP(6) NOT NULL,
    SOGIOLAM FLOAT NOT NULL,
    TANGCA FLOAT NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    GHICHU NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_CHAM_CONG PRIMARY KEY (MACHAMCONG)
);

CREATE TABLE CHI_TIET_BAO_HIEM (
    MAPHIEU NUMBER NOT NULL,
    BHXH_NV NUMBER NOT NULL,
    BHYT_NV NUMBER NOT NULL,
    BHTN_NV NUMBER NOT NULL,
    HUUTRI_DN NUMBER NOT NULL,
    OMDAU_THAISAN_DN NUMBER NOT NULL,
    TNLDBNN_DN NUMBER NOT NULL,
    BHYT_DN NUMBER NOT NULL,
    BHTN_DN NUMBER NOT NULL,
    CONSTRAINT PK_CHI_TIET_BAO_HIEM PRIMARY KEY (MAPHIEU)
);

CREATE TABLE CHI_TIET_DOI_TRA (
    MACHITIET NUMBER NOT NULL,
    MAPHIEU NUMBER NOT NULL,
    MASANPHAM_TRA NUMBER NOT NULL,
    SOLUONG_TRA NUMBER NOT NULL,
    DONGIA_TRA NUMBER NOT NULL,
    MASANPHAM_DOI NUMBER,
    SOLUONG_DOI NUMBER,
    DONGIA_DOI NUMBER,
    GIATRI_CHENH_LECH NUMBER NOT NULL,
    CONSTRAINT PK_CHI_TIET_DOI_TRA PRIMARY KEY (MACHITIET)
);

CREATE TABLE CHI_TIET_DON_HANG (
    MACHITIET NUMBER NOT NULL,
    MASANPHAM NUMBER,
    MADONHANG NUMBER,
    SOLUONG NUMBER,
    DONGIA NUMBER,
    THANHTIEN NUMBER,
    CONSTRAINT PK_CHI_TIET_DON_HANG PRIMARY KEY (MACHITIET)
);

CREATE TABLE CHI_TIET_HOA_DON_BAN_HANG (
    MACHITIET NUMBER NOT NULL,
    MASANPHAM NUMBER,
    MAHOADON NUMBER,
    SOLUONG NUMBER,
    DONGIA NUMBER,
    THANHTIEN NUMBER,
    CONSTRAINT PK_CHI_TIET_HOA_DON_BAN_HANG PRIMARY KEY (MACHITIET)
);

CREATE TABLE CHI_TIET_HOA_DON_MUA_HANG (
    MACHITIET NUMBER NOT NULL,
    MAHOADONMUA NUMBER,
    MASANPHAM NUMBER,
    SOLUONG NUMBER,
    SOLUONGDANHAN NUMBER,
    DONGIA NUMBER,
    THANHTIEN NUMBER,
    CONSTRAINT PK_CHI_TIET_HOA_DON_MUA_HANG PRIMARY KEY (MACHITIET)
);

CREATE TABLE CHI_TIET_KIEM_KE (
    MACHITIET NUMBER NOT NULL,
    MAKIEMKE NUMBER NOT NULL,
    MASANPHAM NUMBER NOT NULL,
    SLHETHONG NUMBER NOT NULL,
    SLTHUCTE NUMBER NOT NULL,
    SLLECH NUMBER NOT NULL,
    LYDOLECH NVARCHAR2(1000),
    CONSTRAINT PK_CHI_TIET_KIEM_KE PRIMARY KEY (MACHITIET)
);

CREATE TABLE CHI_TIET_PHIEU (
    MACHITIET NUMBER NOT NULL,
    SOPHIEU NVARCHAR2(100) NOT NULL,
    MASANPHAM NUMBER NOT NULL,
    SOLUONG NUMBER NOT NULL,
    DONGIA NUMBER NOT NULL,
    MALO NVARCHAR2(100),
    HANSUDUNG DATE,
    THANHTIEN NUMBER NOT NULL,
    CONSTRAINT PK_CHI_TIET_PHIEU PRIMARY KEY (MACHITIET)
);

CREATE TABLE CHI_TIET_THUE_TNCN (
    MACHITIET NUMBER NOT NULL,
    MAPHIEU NUMBER NOT NULL,
    BACTHUE NUMBER NOT NULL,
    THUNHAPCHIUTHUE NUMBER NOT NULL,
    TIENTHUE NUMBER NOT NULL,
    CONSTRAINT PK_CHI_TIET_THUE_TNCN PRIMARY KEY (MACHITIET)
);

CREATE TABLE CUA_HANG (
    MACUAHANG NUMBER NOT NULL,
    TENCUAHANG NVARCHAR2(510) NOT NULL,
    DIACHI NVARCHAR2(1000) NOT NULL,
    SODIENTHOAI NVARCHAR2(40) NOT NULL,
    QUANLY NUMBER NOT NULL,
    CONSTRAINT PK_CUA_HANG PRIMARY KEY (MACUAHANG)
);

CREATE TABLE DANH_MUC (
    MADANHMUC NUMBER NOT NULL,
    TENDANHMUC NVARCHAR2(510) NOT NULL,
    MADANHMUCCHA NUMBER,
    CONSTRAINT PK_DANH_MUC PRIMARY KEY (MADANHMUC)
);

CREATE TABLE DOI_TAC (
    MADOITAC NUMBER NOT NULL,
    TENDOITAC NVARCHAR2(510) NOT NULL,
    SODIENTHOAI NVARCHAR2(40),
    DIACHI NVARCHAR2(1000),
    EMAIL NVARCHAR2(200),
    LOAIDOITAC NVARCHAR2(100),
    CONSTRAINT PK_DOI_TAC PRIMARY KEY (MADOITAC)
);

CREATE TABLE DON_HANG (
    MADONHANG NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    MADOITAC NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAYTAO TIMESTAMP(6) NOT NULL,
    TONGTIENTAMTINH NUMBER NOT NULL,
    DIEMMUONDUNG NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    GHICHU NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_DON_HANG PRIMARY KEY (MADONHANG)
);

CREATE TABLE DON_XIN_NGHI_PHEP (
    MADON NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    LOAINGHI NVARCHAR2(100) NOT NULL,
    TUNGAY DATE NOT NULL,
    DENNGAY DATE NOT NULL,
    SONGAY NUMBER NOT NULL,
    LYDO NVARCHAR2(1000) NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    NGUOIDUYET NUMBER NOT NULL,
    CONSTRAINT PK_DON_XIN_NGHI_PHEP PRIMARY KEY (MADON)
);

CREATE TABLE GIAO_DICH_TIEN (
    MAGIAODICH NUMBER NOT NULL,
    MACUAHANG NUMBER,
    MATAIKHOAN NUMBER NOT NULL,
    LOAIGIAODICH NVARCHAR2(200) NOT NULL,
    SOTIEN NUMBER NOT NULL,
    NGAYGIAODICH TIMESTAMP(6) NOT NULL,
    MAHOADONBAN NUMBER,
    MAHOADONMUA NUMBER,
    MAPHIEULUONG NUMBER,
    MAQUYETTOAN NUMBER,
    MATAIKHOANDOIUNG NUMBER,
    GHICHU NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_GIAO_DICH_TIEN PRIMARY KEY (MAGIAODICH)
);

CREATE TABLE HOA_DON_BAN_HANG (
    MAHOADON NUMBER NOT NULL,
    MADOITAC NUMBER NOT NULL,
    MADONHANG NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    NGAYBAN TIMESTAMP(6) NOT NULL,
    TONGTIEN NUMBER NOT NULL,
    DIEMTICHDUOC NUMBER NOT NULL,
    DIEMSUDUNG NUMBER NOT NULL,
    PHUONGTHUCTHANHTHOAN NVARCHAR2(100) NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    CONSTRAINT PK_HOA_DON_BAN_HANG PRIMARY KEY (MAHOADON)
);

CREATE TABLE HOA_DON_MUA_HANG (
    MAHOADONMUA NUMBER NOT NULL,
    MADOITAC NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    SOHOADON_VAT NVARCHAR2(100) NOT NULL,
    NGAYLAP DATE NOT NULL,
    TONGTIEN NUMBER NOT NULL,
    PHUONGTHUCTHANHTOAN NVARCHAR2(100) NOT NULL,
    TRANGTHAI_THANHTOAN NVARCHAR2(100) NOT NULL,
    GHICHU NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_HOA_DON_MUA_HANG PRIMARY KEY (MAHOADONMUA)
);

CREATE TABLE HO_SO_LUONG (
    MANHANVIEN NUMBER NOT NULL,
    MUCLUONG NUMBER NOT NULL,
    GIAMTRUBANTHAN NUMBER NOT NULL,
    SONGUOIPHUTHUOC NUMBER NOT NULL,
    TIENGIAMNPT NUMBER NOT NULL,
    NGAYCAPNHAP DATE NOT NULL,
    CONSTRAINT PK_HO_SO_LUONG PRIMARY KEY (MANHANVIEN)
);

CREATE TABLE KHACH_HANG (
    MADOITAC NUMBER NOT NULL,
    DIEMTICHLUY NUMBER NOT NULL,
    NGAYTHAMGIA DATE NOT NULL,
    LOAIKHACHHANG NVARCHAR2(100) NOT NULL,
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MADOITAC)
);

CREATE TABLE KHO (
    MAKHO NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    TENKHO NVARCHAR2(510) NOT NULL,
    DIACHI NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_KHO PRIMARY KEY (MAKHO)
);

CREATE TABLE KIEM_KE (
    MAKIEMKE NUMBER NOT NULL,
    MAKHO NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    NGAYKIEMKE DATE NOT NULL,
    NGUOIKIEMKE NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    CONSTRAINT PK_KIEM_KE PRIMARY KEY (MAKIEMKE)
);

CREATE TABLE NHANVIEN (
    MANHANVIEN NUMBER NOT NULL,
    MACUAHANG NUMBER,
    HOTEN NVARCHAR2(510) NOT NULL,
    SDT NVARCHAR2(40) NOT NULL,
    EMAIL NVARCHAR2(200) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANHANVIEN)
);

CREATE TABLE NHA_CUNG_CAP (
    MADOITAC NUMBER NOT NULL,
    MASOTHEU NVARCHAR2(100) NOT NULL,
    DIEUKHOANTHANHTOAN NVARCHAR2(510) NOT NULL,
    GHICHU NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MADOITAC)
);

CREATE TABLE PHAN_QUYEN_NHAN_VIEN (
    MAVAITRO NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAYGAN DATE NOT NULL,
    CONSTRAINT PK_PHAN_QUYEN_NHAN_VIEN PRIMARY KEY (MAVAITRO, MANHANVIEN)
);

CREATE TABLE PHIEU_DOI_TRA (
    MAPHIEU NUMBER NOT NULL,
    MADONHANG NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    MADOITAC NUMBER NOT NULL,
    MANHANVIEN_TAO NUMBER NOT NULL,
    MANHANVIEN_DUYET NUMBER,
    LOAI_PHIEU NVARCHAR2(100) NOT NULL,
    TRANG_THAI NVARCHAR2(100) NOT NULL,
    TONGTIEN_HOAN NUMBER,
    TONGTIEN_THU_THEM NUMBER,
    NGAYTAO TIMESTAMP(6) NOT NULL,
    NGAYDUYET TIMESTAMP(6),
    LYDO NVARCHAR2(1000) NOT NULL,
    CONSTRAINT PK_PHIEU_DOI_TRA PRIMARY KEY (MAPHIEU)
);

CREATE TABLE PHIEU_KHO (
    SOPHIEU NVARCHAR2(100) NOT NULL,
    LOAIPHIEU NVARCHAR2(100) NOT NULL,
    MAHOADON NUMBER,
    NGAYLAP DATE NOT NULL,
    NGAYTHUCPHE DATE NOT NULL,
    KHODI NUMBER,
    KHODEN NUMBER,
    DOITAC NUMBER NOT NULL,
    TONGGIATRIPHIEU NUMBER NOT NULL,
    NGUOIPHUTRACH NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(200) NOT NULL,
    CONSTRAINT PK_PHIEU_KHO PRIMARY KEY (SOPHIEU)
);

CREATE TABLE PHIEU_LUONG (
    MAPHIEU NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    THANGNAM NVARCHAR2(20) NOT NULL,
    LUONG NUMBER NOT NULL,
    TONGBAOHIEMNV NUMBER NOT NULL,
    TONGTHUETNCN NUMBER NOT NULL,
    THUCLINH NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    CONSTRAINT PK_PHIEU_LUONG PRIMARY KEY (MAPHIEU)
);

CREATE TABLE QUAN_LY_CHI_NHANH (
    MACUAHANG NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    CONSTRAINT PK_QUAN_LY_CHI_NHANH PRIMARY KEY (MACUAHANG, MANHANVIEN)
);

CREATE TABLE QUAN_LY_PHEP (
    IDPHEP NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NAM NUMBER NOT NULL,
    TONGPHEP NUMBER NOT NULL,
    DADUNG NUMBER NOT NULL,
    CONLAI NUMBER NOT NULL,
    CONSTRAINT PK_QUAN_LY_PHEP PRIMARY KEY (IDPHEP)
);

CREATE TABLE QUYET_TOAN_THUE_BH (
    MAPHIEU NUMBER NOT NULL,
    MAQUYETTOAN NUMBER NOT NULL,
    THUETNCN_NOPHO NUMBER NOT NULL,
    BHBB_NV NUMBER NOT NULL,
    BHBB_DV NUMBER NOT NULL,
    TONGNOPNSNN NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL,
    CONSTRAINT PK_QUYET_TOAN_THUE_BH PRIMARY KEY (MAPHIEU, MAQUYETTOAN)
);

CREATE TABLE SAN_PHAM (
    MASANPHAM NUMBER NOT NULL,
    TENSANPHAM VARCHAR2(500) NOT NULL,
    DONVITINH NVARCHAR2(100) NOT NULL,
    GIANIEMYET NUMBER NOT NULL,
    THUE FLOAT NOT NULL,
    MAVACH NVARCHAR2(200) NOT NULL,
    COTHEMUA NUMBER NOT NULL,
    COTHEBAN NUMBER NOT NULL,
    POS NUMBER NOT NULL,
    THUONGHIEU NVARCHAR2(510) NOT NULL,
    XUATXU NVARCHAR2(510) NOT NULL,
    PHUHOP NVARCHAR2(510) NOT NULL,
    THANHPHAN CLOB NOT NULL,
    HUONGDAN CLOB NOT NULL,
    MOTA CLOB NOT NULL,
    HINHANH NVARCHAR2(2000),
    CONSTRAINT PK_SAN_PHAM PRIMARY KEY (MASANPHAM)
);

CREATE TABLE SAN_PHAM_DANH_MUC (
    MASANPHAM NUMBER NOT NULL,
    MADANHMUC NUMBER NOT NULL,
    CONSTRAINT PK_SAN_PHAM_DANH_MUC PRIMARY KEY (MASANPHAM, MADANHMUC)
);

CREATE TABLE TAI_KHOAN (
    MATAIKHOAN NUMBER NOT NULL,
    MACUAHANG NUMBER,
    TENTAIKHOAN NVARCHAR2(510) NOT NULL,
    LOAITAIKHOAN NVARCHAR2(100) NOT NULL,
    SOTAIKHOAN NVARCHAR2(100),
    TENNGANHANG NVARCHAR2(510),
    SODUHIENTAI NUMBER NOT NULL,
    MUCDICH NVARCHAR2(200) NOT NULL,
    CONSTRAINT PK_TAI_KHOAN PRIMARY KEY (MATAIKHOAN)
);

CREATE TABLE TAI_KHOAN_NHAN_VIEN (
    MANHANVIEN NUMBER NOT NULL,
    USERNAME NVARCHAR2(200) NOT NULL,
    PASSWORDHASH NVARCHAR2(510) NOT NULL,
    PASSWORDHASHHISTORY NVARCHAR2(2000) NOT NULL,
    NGAYTAO DATE NOT NULL,
    LAST_LOGIN TIMESTAMP(6) NOT NULL,
    TRANG_THAI NUMBER NOT NULL,
    CONSTRAINT PK_TAI_KHOAN_NHAN_VIEN PRIMARY KEY (MANHANVIEN)
);

CREATE TABLE TON_KHO (
    MASANPHAM NUMBER NOT NULL,
    MAKHO NUMBER NOT NULL,
    SOLUONGTON NUMBER NOT NULL,
    NGAYCAPNHAP TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_TON_KHO PRIMARY KEY (MASANPHAM, MAKHO)
);

CREATE TABLE VAI_TRO (
    MAVAITRO NUMBER NOT NULL,
    TENVAITRO NVARCHAR2(200) NOT NULL,
    QUYENHAN CLOB NOT NULL,
    CONSTRAINT PK_VAI_TRO PRIMARY KEY (MAVAITRO)
);


-- ============================================================
-- PHẦN 2: FOREIGN KEY CONSTRAINTS
-- ============================================================

ALTER TABLE CHAM_CONG
    ADD CONSTRAINT FK_MANHANVIEN_CC_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE CHI_TIET_BAO_HIEM
    ADD CONSTRAINT FK_MAPHIEU_CTBH_PL
    FOREIGN KEY (MAPHIEU)
    REFERENCES PHIEU_LUONG;

ALTER TABLE CHI_TIET_DOI_TRA
    ADD CONSTRAINT FK_MAPHIEU_CTDT_PDT
    FOREIGN KEY (MAPHIEU)
    REFERENCES PHIEU_DOI_TRA;

ALTER TABLE CHI_TIET_DON_HANG
    ADD CONSTRAINT FK_MADONHANG_CTDH_DH
    FOREIGN KEY (MADONHANG)
    REFERENCES DON_HANG;

ALTER TABLE CHI_TIET_DON_HANG
    ADD CONSTRAINT FK_MASANPHAM_CTDH_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG
    ADD CONSTRAINT FK_MAHOADON_CTHDBH_HDBH
    FOREIGN KEY (MAHOADON)
    REFERENCES HOA_DON_BAN_HANG;

ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG
    ADD CONSTRAINT FK_MASANPHAM_CTHDBH_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG
    ADD CONSTRAINT FK_MASANPHAM_CTHDMH_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG
    ADD CONSTRAINT FK_MAHOADONMUA_CTHDMH_HDMH
    FOREIGN KEY (MAHOADONMUA)
    REFERENCES HOA_DON_MUA_HANG;

ALTER TABLE CHI_TIET_KIEM_KE
    ADD CONSTRAINT FK_MAKIEMKE_CTKK_KK
    FOREIGN KEY (MAKIEMKE)
    REFERENCES KIEM_KE;

ALTER TABLE CHI_TIET_KIEM_KE
    ADD CONSTRAINT FK_MASANPHAM_CTKK_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE CHI_TIET_PHIEU
    ADD CONSTRAINT FK_MASANPHAM_CTP_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE CHI_TIET_PHIEU
    ADD CONSTRAINT FK_SOPHIEU_CTP_PK
    FOREIGN KEY (SOPHIEU)
    REFERENCES PHIEU_KHO;

ALTER TABLE CHI_TIET_THUE_TNCN
    ADD CONSTRAINT FK_MAPHIEU_CTTNCN_PL
    FOREIGN KEY (MAPHIEU)
    REFERENCES PHIEU_LUONG;

ALTER TABLE DANH_MUC
    ADD CONSTRAINT FK_MADANHMUCCHA_DM_DM
    FOREIGN KEY (MADANHMUCCHA)
    REFERENCES DANH_MUC;

ALTER TABLE DON_HANG
    ADD CONSTRAINT FK_MACUAHANG_DH_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE DON_HANG
    ADD CONSTRAINT FK_MADOITAC_DH_KH
    FOREIGN KEY (MADOITAC)
    REFERENCES KHACH_HANG;

ALTER TABLE DON_HANG
    ADD CONSTRAINT FK_MANHANVIEN_DH_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE DON_XIN_NGHI_PHEP
    ADD CONSTRAINT FK_MANHANVIEN_DXNP_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE DON_XIN_NGHI_PHEP
    ADD CONSTRAINT FK_NGUOIDUYET_DXNP_NV
    FOREIGN KEY (NGUOIDUYET)
    REFERENCES NHANVIEN;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MAHOADONMUA_GDT_HDMH
    FOREIGN KEY (MAHOADONMUA)
    REFERENCES HOA_DON_MUA_HANG;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MAHOADONBAN_GDT_HDBH
    FOREIGN KEY (MAHOADONBAN)
    REFERENCES HOA_DON_BAN_HANG;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MAPHIEULUONG_GDT_PL
    FOREIGN KEY (MAPHIEULUONG)
    REFERENCES PHIEU_LUONG;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MATAIKHOAN_GDT_TK
    FOREIGN KEY (MATAIKHOAN)
    REFERENCES TAI_KHOAN;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MATAIKHOANDOIUNG_GDT_TK
    FOREIGN KEY (MATAIKHOANDOIUNG)
    REFERENCES TAI_KHOAN;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MAQUYETTOAN_GDT_QTTBH
    FOREIGN KEY (MAQUYETTOAN)
    REFERENCES QUYET_TOAN_THUE_BH;

ALTER TABLE GIAO_DICH_TIEN
    ADD CONSTRAINT FK_MACUAHANG_GDT_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE HOA_DON_BAN_HANG
    ADD CONSTRAINT FK_MADOITAC_HDBH_KH
    FOREIGN KEY (MADOITAC)
    REFERENCES KHACH_HANG;

ALTER TABLE HOA_DON_BAN_HANG
    ADD CONSTRAINT FK_MADONHANG_HDBH_DH
    FOREIGN KEY (MADONHANG)
    REFERENCES DON_HANG;

ALTER TABLE HOA_DON_BAN_HANG
    ADD CONSTRAINT FK_MANHANVIEN_HDBH_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE HOA_DON_BAN_HANG
    ADD CONSTRAINT FK_MACUAHANG_HDBH_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE HOA_DON_MUA_HANG
    ADD CONSTRAINT FK_MANHANVIEN_HDMH_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE HOA_DON_MUA_HANG
    ADD CONSTRAINT FK_MADOITAC_HDMH_NCC
    FOREIGN KEY (MADOITAC)
    REFERENCES NHA_CUNG_CAP;

ALTER TABLE HO_SO_LUONG
    ADD CONSTRAINT FK_MANHANVIEN_HSL_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE KHACH_HANG
    ADD CONSTRAINT FK_MADOITAC_KH_DT
    FOREIGN KEY (MADOITAC)
    REFERENCES DOI_TAC;

ALTER TABLE KHO
    ADD CONSTRAINT FK_MACUAHANG_KHO_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE KIEM_KE
    ADD CONSTRAINT FK_MACUAHANG_KK_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE KIEM_KE
    ADD CONSTRAINT FK_MAKHO_KK_KHO
    FOREIGN KEY (MAKHO)
    REFERENCES KHO;

ALTER TABLE NHANVIEN
    ADD CONSTRAINT FK_MACUAHANG_NV_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE NHA_CUNG_CAP
    ADD CONSTRAINT FK_MADOITAC_NCC_DT
    FOREIGN KEY (MADOITAC)
    REFERENCES DOI_TAC;

ALTER TABLE PHAN_QUYEN_NHAN_VIEN
    ADD CONSTRAINT FK_MAVAITRO_PQNV_VT
    FOREIGN KEY (MAVAITRO)
    REFERENCES VAI_TRO;

ALTER TABLE PHAN_QUYEN_NHAN_VIEN
    ADD CONSTRAINT FK_MANHANVIEN_PQNV_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE PHIEU_DOI_TRA
    ADD CONSTRAINT FK_MADOITAC_PDT_KH
    FOREIGN KEY (MADOITAC)
    REFERENCES KHACH_HANG;

ALTER TABLE PHIEU_DOI_TRA
    ADD CONSTRAINT FK_MADONHANG_PDT_DH
    FOREIGN KEY (MADONHANG)
    REFERENCES DON_HANG;

ALTER TABLE PHIEU_DOI_TRA
    ADD CONSTRAINT FK_MACUAHANG_PDT_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE PHIEU_KHO
    ADD CONSTRAINT FK_KHODI_PK_KHO
    FOREIGN KEY (KHODI)
    REFERENCES KHO;

ALTER TABLE PHIEU_KHO
    ADD CONSTRAINT FK_NGUOIPHUTRACH_PK_NV
    FOREIGN KEY (NGUOIPHUTRACH)
    REFERENCES NHANVIEN;

ALTER TABLE PHIEU_KHO
    ADD CONSTRAINT FK_DOITAC_PK_DT
    FOREIGN KEY (DOITAC)
    REFERENCES DOI_TAC;

ALTER TABLE PHIEU_KHO
    ADD CONSTRAINT FK_KHODEN_PK_KHO
    FOREIGN KEY (KHODEN)
    REFERENCES KHO;

ALTER TABLE PHIEU_LUONG
    ADD CONSTRAINT FK_MANHANVIEN_PL_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE QUAN_LY_CHI_NHANH
    ADD CONSTRAINT FK_MANHANVIEN_QLCN_TKNV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES TAI_KHOAN_NHAN_VIEN;

ALTER TABLE QUAN_LY_CHI_NHANH
    ADD CONSTRAINT FK_MACUAHANG_QLCN_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE QUAN_LY_PHEP
    ADD CONSTRAINT FK_MANHANVIEN_QLP_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE QUYET_TOAN_THUE_BH
    ADD CONSTRAINT FK_MAPHIEU_QTTBH_PL
    FOREIGN KEY (MAPHIEU)
    REFERENCES PHIEU_LUONG;

ALTER TABLE SAN_PHAM_DANH_MUC
    ADD CONSTRAINT FK_MASANPHAM_SPDM_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE SAN_PHAM_DANH_MUC
    ADD CONSTRAINT FK_MADANHMUC_SPDM_DM
    FOREIGN KEY (MADANHMUC)
    REFERENCES DANH_MUC;

ALTER TABLE TAI_KHOAN
    ADD CONSTRAINT FK_MACUAHANG_TK_CH
    FOREIGN KEY (MACUAHANG)
    REFERENCES CUA_HANG;

ALTER TABLE TAI_KHOAN_NHAN_VIEN
    ADD CONSTRAINT FK_MANHANVIEN_TKNV_NV
    FOREIGN KEY (MANHANVIEN)
    REFERENCES NHANVIEN;

ALTER TABLE TON_KHO
    ADD CONSTRAINT FK_MASANPHAM_TK_SP
    FOREIGN KEY (MASANPHAM)
    REFERENCES SAN_PHAM;

ALTER TABLE TON_KHO
    ADD CONSTRAINT FK_MAKHO_TK_KHO
    FOREIGN KEY (MAKHO)
    REFERENCES KHO;