-- 1. Một PHIEU_KHO có nhiều CHI_TIET_PHIEU (1:n)
ALTER TABLE CHI_TIET_PHIEU ADD CONSTRAINT SOPHIEU_CTP_PK 
FOREIGN KEY (SOPHIEU) REFERENCES PHIEU_KHO(SOPHIEU);

-- 2. Một SAN_PHAM có nhiều CHI_TIET_PHIEU (1:n)
ALTER TABLE CHI_TIET_PHIEU ADD CONSTRAINT MASANPHAM_CTP_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 3. Một HOA_DON_BAN_HANG có nhiều CHI_TIET_HOA_DON_BAN_HANG (1:n)
ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG ADD CONSTRAINT MAHOADON_CTHDBH_HDBH 
FOREIGN KEY (MAHOADON) REFERENCES HOA_DON_BAN_HANG(MAHOADON);

-- 4. Một SAN_PHAM có nhiều CHI_TIET_HOA_DON_BAN_HANG (1:n)
ALTER TABLE CHI_TIET_HOA_DON_BAN_HANG ADD CONSTRAINT MASANPHAM_CTHDBH_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 5. Một DOI_TAC có một KHACH_HANG (1:1)
ALTER TABLE KHACH_HANG ADD CONSTRAINT MADOITAC_KH_DT 
FOREIGN KEY (MADOITAC) REFERENCES DOI_TAC(MADOITAC);

-- 6. Một DOI_TAC có một NHA_CUNG_CAP (1:1)
ALTER TABLE NHA_CUNG_CAP ADD CONSTRAINT MADOITAC_NCC_DT 
FOREIGN KEY (MADOITAC) REFERENCES DOI_TAC(MADOITAC);

-- 7. Một KHACH_HANG có nhiều HOA_DON_BAN_HANG (1:n)
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT MADOITAC_HDBH_KH 
FOREIGN KEY (MADOITAC) REFERENCES KHACH_HANG(MADOITAC);

-- 8. Một NHANVIEN có nhiều PHAN_QUYEN_NHAN_VIEN (1:n)
ALTER TABLE PHAN_QUYEN_NHAN_VIEN ADD CONSTRAINT MANHANVIEN_PQNV_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 9. Một VAI_TRO có một PHAN_QUYEN_NHAN_VIEN (1:1)
ALTER TABLE PHAN_QUYEN_NHAN_VIEN ADD CONSTRAINT MAVAITRO_PQNV_VT 
FOREIGN KEY (MAVAITRO) REFERENCES VAI_TRO(MAVAITRO);

-- 10. Một NHANVIEN có nhiều PHIEU_KHO (1:n)
ALTER TABLE PHIEU_KHO ADD CONSTRAINT NGUOIPHUTRACH_PK_NV 
FOREIGN KEY (NGUOIPHUTRACH) REFERENCES NHANVIEN(MANHANVIEN);

-- 11. Một NHANVIEN có nhiều HOA_DON_BAN_HANG (1:n)
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT MANHANVIEN_HDBH_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 12. Một NHANVIEN có một HO_SO_LUONG (1:1)
ALTER TABLE HO_SO_LUONG ADD CONSTRAINT MANHANVIEN_HSL_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 13. Một NHANVIEN có nhiều PHIEU_LUONG (1:n)
ALTER TABLE PHIEU_LUONG ADD CONSTRAINT MANHANVIEN_PL_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 14. Một PHIEU_LUONG có một QUYET_TOAN_THUE_BH (1:1)
ALTER TABLE QUYET_TOAN_THUE_BH ADD CONSTRAINT MAPHIEU_QTTBH_PL 
FOREIGN KEY (MAPHIEU) REFERENCES PHIEU_LUONG(MAPHIEU);

-- 15. Một PHIEU_LUONG có một CHI_TIET_BAO_HIEM (1:1)
ALTER TABLE CHI_TIET_BAO_HIEM ADD CONSTRAINT MAPHIEU_CTBH_PL 
FOREIGN KEY (MAPHIEU) REFERENCES PHIEU_LUONG(MAPHIEU);

-- 16. Một PHIEU_LUONG có nhiều CHI_TIET_THUE_TNCN (1:n)
ALTER TABLE CHI_TIET_THUE_TNCN ADD CONSTRAINT MAPHIEU_CTTNCN_PL 
FOREIGN KEY (MAPHIEU) REFERENCES PHIEU_LUONG(MAPHIEU);

-- 17. Một NHANVIEN có nhiều CHAM_CONG (1:n)
ALTER TABLE CHAM_CONG ADD CONSTRAINT MANHANVIEN_CC_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 18. Một NHANVIEN có nhiều QUAN_LY_PHEP (1:n)
ALTER TABLE QUAN_LY_PHEP ADD CONSTRAINT MANHANVIEN_QLP_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 19. Một NHANVIEN có nhiều DON_XIN_NGHI_PHEP (Người lập) (1:n)
ALTER TABLE DON_XIN_NGHI_PHEP ADD CONSTRAINT MANHANVIEN_DXNP_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 20. Một NHANVIEN có nhiều DON_XIN_NGHI_PHEP (Người duyệt) (1:n)
ALTER TABLE DON_XIN_NGHI_PHEP ADD CONSTRAINT NGUOIDUYET_DXNP_NV 
FOREIGN KEY (NGUOIDUYET) REFERENCES NHANVIEN(MANHANVIEN);

-- 21. Một NHANVIEN có một TAI_KHOAN_NHAN_VIEN (1:1)
ALTER TABLE TAI_KHOAN_NHAN_VIEN ADD CONSTRAINT MANHANVIEN_TKNV_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 22. Một DON_HANG có một HOA_DON_BAN_HANG (1:1)
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT MADONHANG_HDBH_DH 
FOREIGN KEY (MADONHANG) REFERENCES DON_HANG(MADONHANG);

-- 23. Một NHANVIEN có nhiều DON_HANG (1:n)
ALTER TABLE DON_HANG ADD CONSTRAINT MANHANVIEN_DH_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 24. Một KHACH_HANG có nhiều DON_HANG (1:n)
ALTER TABLE DON_HANG ADD CONSTRAINT MADOITAC_DH_KH 
FOREIGN KEY (MADOITAC) REFERENCES KHACH_HANG(MADOITAC);

-- 25. Một SAN_PHAM có nhiều CHI_TIET_DON_HANG (1:n)
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT MASANPHAM_CTDH_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 26. Một DON_HANG có nhiều CHI_TIET_DON_HANG (1:n)
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT MADONHANG_CTDH_DH 
FOREIGN KEY (MADONHANG) REFERENCES DON_HANG(MADONHANG);

-- 27. Một NHANVIEN có nhiều HOA_DON_MUA_HANG (1:n)
ALTER TABLE HOA_DON_MUA_HANG ADD CONSTRAINT MANHANVIEN_HDMH_NV 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);

-- 28. Một NHA_CUNG_CAP có nhiều HOA_DON_MUA_HANG (1:n)
ALTER TABLE HOA_DON_MUA_HANG ADD CONSTRAINT MADOITAC_HDMH_NCC 
FOREIGN KEY (MADOITAC) REFERENCES NHA_CUNG_CAP(MADOITAC);

-- 29. Một HOA_DON_MUA_HANG có nhiều PHIEU_KHO (1:n)
ALTER TABLE PHIEU_KHO ADD CONSTRAINT MAHOADON_PK_HDMH 
FOREIGN KEY (MAHOADON) REFERENCES HOA_DON_MUA_HANG(MAHOADONMUA);

-- 30. Một HOA_DON_MUA_HANG có nhiều CHI_TIET_HOA_DON_MUA_HANG (1:n)
ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG ADD CONSTRAINT MAHOADONMUA_CTHDMH_HDMH 
FOREIGN KEY (MAHOADONMUA) REFERENCES HOA_DON_MUA_HANG(MAHOADONMUA);

-- 31. Một SAN_PHAM có nhiều CHI_TIET_HOA_DON_MUA_HANG (1:n)
ALTER TABLE CHI_TIET_HOA_DON_MUA_HANG ADD CONSTRAINT MASANPHAM_CTHDMH_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 32. Một NHA_CUNG_CAP có nhiều PHIEU_KHO (1:n)
ALTER TABLE PHIEU_KHO ADD CONSTRAINT DOITAC_PK_NCC 
FOREIGN KEY (DOITAC) REFERENCES NHA_CUNG_CAP(MADOITAC);

-- 33. Một SAN_PHAM có một TON_KHO (1:1)
ALTER TABLE TON_KHO ADD CONSTRAINT MASANPHAM_TK_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 34. Một KHO có một TON_KHO (1:1)
ALTER TABLE TON_KHO ADD CONSTRAINT MAKHO_TK_KHO 
FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO);

-- 35. Một KHO có nhiều PHIEU_KHO (Kho đi) (1:n)
ALTER TABLE PHIEU_KHO ADD CONSTRAINT KHODI_PK_KHO 
FOREIGN KEY (KHODI) REFERENCES KHO(MAKHO);

-- 36. Một KHO có nhiều PHIEU_KHO (Kho đến) (1:n)
ALTER TABLE PHIEU_KHO ADD CONSTRAINT KHODEN_PK_KHO 
FOREIGN KEY (KHODEN) REFERENCES KHO(MAKHO);

-- 37. Một KHO có nhiều KIEM_KE (1:n)
ALTER TABLE KIEM_KE ADD CONSTRAINT MAKHO_KK_KHO 
FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO);

-- 38. Một KIEM_KE có nhiều CHI_TIET_KIEM_KE (1:n)
ALTER TABLE CHI_TIET_KIEM_KE ADD CONSTRAINT MAKIEMKE_CTKK_KK 
FOREIGN KEY (MAKIEMKE) REFERENCES KIEM_KE(MAKIEMKE);

-- 39. Một SAN_PHAM có nhiều CHI_TIET_KIEM_KE (1:n)
ALTER TABLE CHI_TIET_KIEM_KE ADD CONSTRAINT MASANPHAM_CTKK_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 40. Một TAI_KHOAN có nhiều GIAO_DICH_TIEN (Tài khoản chính) (1:n)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MATAIKHOAN_GDT_TK 
FOREIGN KEY (MATAIKHOAN) REFERENCES TAI_KHOAN(MATAIKHOAN);

-- 41. Một TAI_KHOAN có nhiều GIAO_DICH_TIEN (Đối ứng) (1:n)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MATAIKHOANDOIUNG_GDT_TK 
FOREIGN KEY (MATAIKHOANDOIUNG) REFERENCES TAI_KHOAN(MATAIKHOAN);

-- 42. Một HOA_DON_BAN_HANG có nhiều GIAO_DICH_TIEN (1:n)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MAHOADONBAN_GDT_HDBH 
FOREIGN KEY (MAHOADONBAN) REFERENCES HOA_DON_BAN_HANG(MAHOADON);

-- 43. Một HOA_DON_MUA_HANG có nhiều GIAO_DICH_TIEN (1:n)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MAHOADONMUA_GDT_HDMH 
FOREIGN KEY (MAHOADONMUA) REFERENCES HOA_DON_MUA_HANG(MAHOADONMUA);

-- 44. Một PHIEU_LUONG có một GIAO_DICH_TIEN (1:1)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MAPHIEULUONG_GDT_PL 
FOREIGN KEY (MAPHIEULUONG) REFERENCES PHIEU_LUONG(MAPHIEU);

-- 45. Một QUYET_TOAN_THUE_BH có một GIAO_DICH_TIEN (1:1)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MAQUYETTOAN_GDT_QTTBH 
FOREIGN KEY (MAQUYETTOAN) REFERENCES QUYET_TOAN_THUE_BH(MAQUYETTOAN);

-- 46. Một CUA_HANG có nhiều DON_HANG (1:n)
ALTER TABLE DON_HANG ADD CONSTRAINT MACUAHANG_DH_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 47. Một CUA_HANG có nhiều HOA_DON_BAN_HANG (1:n)
ALTER TABLE HOA_DON_BAN_HANG ADD CONSTRAINT MACUAHANG_HDBH_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 48. Một CUA_HANG có nhiều KHO (1:n)
ALTER TABLE KHO ADD CONSTRAINT MACUAHANG_KHO_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 49. Một CUA_HANG có nhiều KIEM_KE (1:n)
ALTER TABLE KIEM_KE ADD CONSTRAINT MACUAHANG_KK_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 50. Một CUA_HANG có nhiều TAI_KHOAN (1:n)
ALTER TABLE TAI_KHOAN ADD CONSTRAINT MACUAHANG_TK_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 51. Một CUA_HANG có nhiều GIAO_DICH_TIEN (1:n)
ALTER TABLE GIAO_DICH_TIEN ADD CONSTRAINT MACUAHANG_GDT_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 52. Một CUA_HANG có nhiều NHANVIEN (1:n)
ALTER TABLE NHANVIEN ADD CONSTRAINT MACUAHANG_NV_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 53. Một CUA_HANG có một QUAN_LY_CHI_NHANH (1:1)
ALTER TABLE QUAN_LY_CHI_NHANH ADD CONSTRAINT MACUAHANG_QLCN_CH 
FOREIGN KEY (MACUAHANG) REFERENCES CUA_HANG(MACUAHANG);

-- 54. Một TAI_KHOAN_NHAN_VIEN có một QUAN_LY_CHI_NHANH (1:1)
ALTER TABLE QUAN_LY_CHI_NHANH ADD CONSTRAINT MANHANVIEN_QLCN_TKNV 
FOREIGN KEY (MANHANVIEN) REFERENCES TAI_KHOAN_NHAN_VIEN(MANHANVIEN);

-- 55. Một DANH_MUC có nhiều DANH_MUC (Đệ quy cha-con) (1:n)
ALTER TABLE DANH_MUC ADD CONSTRAINT MADANHMUCCHA_DM_DM 
FOREIGN KEY (MADANHMUCCHA) REFERENCES DANH_MUC(MADANHMUC);

-- 56. Một SAN_PHAM có một SAN_PHAM_DANH_MUC (1:1)
ALTER TABLE SAN_PHAM_DANH_MUC ADD CONSTRAINT MASANPHAM_SPDM_SP 
FOREIGN KEY (MASANPHAM) REFERENCES SAN_PHAM(MASANPHAM);

-- 57. Một DANH_MUC có một SAN_PHAM_DANH_MUC (1:1)
ALTER TABLE SAN_PHAM_DANH_MUC ADD CONSTRAINT MADANHMUC_SPDM_DM 
FOREIGN KEY (MADANHMUC) REFERENCES DANH_MUC(MADANHMUC);
