CREATE TABLE QUYET_TOAN_THUE_BH (
    MAPHIEU NUMBER NOT NULL,
    MAQUYETTOAN NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    THUETNCN_NOPHO NUMBER(19,0) NOT NULL,
    BHBB_NV NUMBER(19,0) NOT NULL,
    BHBB_DV NUMBER(19,0) NOT NULL,
    TONGNOPNSNN NUMBER(19,0) NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL
);

CREATE TABLE CHI_TIET_BAO_HIEM (
    MAPHIEU NUMBER PRIMARY KEY,
    BHXH_NV NUMBER(19,0) NOT NULL,
    BHYT_NV NUMBER(19,0) NOT NULL,
    BHTN_NV NUMBER(19,0) NOT NULL,
    HUUTRI_DN NUMBER(19,0) NOT NULL,
    OMDAU_THAISAN_DN NUMBER(19,0) NOT NULL,
    TNLDBNN_DN NUMBER(19,0) NOT NULL,
    BHYT_DN NUMBER(19,0) NOT NULL,
    BHTN_DN NUMBER(19,0) NOT NULL
);

CREATE TABLE CHI_TIET_THUE_TNCN (
    MACHITIET NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MAPHIEU NUMBER NOT NULL,
    BACTHUE NUMBER NOT NULL,
    THUNHAPCHIUTHUE NUMBER(19,0) NOT NULL,
    TIENTHUE NUMBER(19,0) NOT NULL
);
