CREATE TABLE HO_SO_LUONG (
    MANHANVIEN NUMBER PRIMARY KEY,
    MUCLUONG NUMBER(19,0) NOT NULL,
    GIAMTRUBANTHAN NUMBER(19,0) DEFAULT 15500000 NOT NULL,
    SONGUOIPHUTHUOC NUMBER DEFAULT 0 NOT NULL,
    TIENGIAMNPT NUMBER(19,0) NOT NULL,
    NGAYCAPNHAP DATE NOT NULL
);

CREATE TABLE PHIEU_LUONG (
    MAPHIEU NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MANHANVIEN NUMBER NOT NULL,
    THANGNAM NVARCHAR2(10) NOT NULL,
    LUONG NUMBER(19,0) NOT NULL,
    TONGBAOHIEMNV NUMBER(19,0) NOT NULL,
    TONGTHUETNCN NUMBER(19,0) NOT NULL,
    THUCLINH NUMBER(19,0) NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL
);
