CREATE TABLE PHIEU_KHO (
    SOPHIEU NVARCHAR2(50) PRIMARY KEY,
    LOAIPHIEU NVARCHAR2(50) NOT NULL,
    MAHOADON NUMBER,
    NGAYLAP DATE NOT NULL,
    NGAYTHUCPHE DATE NOT NULL,
    KHODI NUMBER,
    KHODEN NUMBER,
    DOITAC NUMBER NOT NULL,
    TONGGIATRIPHIEU NUMBER(19,0) NOT NULL,
    NGUOIPHUTRACH NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(100) NOT NULL
);

CREATE TABLE CHI_TIET_PHIEU (
    MACHITIET NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    SOPHIEU NVARCHAR2(50) NOT NULL,
    MASANPHAM NUMBER NOT NULL,
    SOLUONG NUMBER NOT NULL,
    DONGIA NUMBER(19,0) NOT NULL,
    MALO NVARCHAR2(50),
    HANSUDUNG DATE,
    THANHTIEN NUMBER(19,0) NOT NULL
);

CREATE TABLE KHO (
    MAKHO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MACUAHANG NUMBER NOT NULL,
    TENKHO NVARCHAR2(255) NOT NULL,
    DIACHI NVARCHAR2(500) NOT NULL
);

CREATE TABLE TON_KHO (
    MASANPHAM NUMBER NOT NULL,
    MAKHO NUMBER NOT NULL,
    SOLUONGTON NUMBER NOT NULL,
    NGAYCAPNHAP TIMESTAMP NOT NULL,
    PRIMARY KEY (MASANPHAM, MAKHO)
);

CREATE TABLE KIEM_KE (
    MAKIEMKE NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MAKHO NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    NGAYKIEMKE DATE NOT NULL,
    NGUOIKIEMKE NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL
);

CREATE TABLE CHI_TIET_KIEM_KE (
    MACHITIET NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MAKIEMKE NUMBER NOT NULL,
    MASANPHAM NUMBER NOT NULL,
    SLHETHONG NUMBER NOT NULL,
    SLTHUCTE NUMBER NOT NULL,
    SLLECH NUMBER NOT NULL,
    LYDOLECH NVARCHAR2(500)
);