CREATE TABLE CUA_HANG (
    MACUAHANG NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TENCUAHANG NVARCHAR2(255) NOT NULL,
    DIACHI NVARCHAR2(500) NOT NULL,
    SODIENTHOAI NVARCHAR2(20) NOT NULL,
    QUANLY NUMBER NOT NULL
);