CREATE TABLE HOA_DON_MUA_HANG (
    MAHOADONMUA NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MADOITAC NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    SOHOADON_VAT NVARCHAR2(50) NOT NULL,
    NGAYLAP DATE NOT NULL,
    TONGTIEN NUMBER(19,0) NOT NULL,
    PHUONGTHUCTHANHTOAN NVARCHAR2(50) NOT NULL,
    TRANGTHAI_THANHTOAN NVARCHAR2(50) NOT NULL,
    GHICHU NVARCHAR2(500) NOT NULL
);


CREATE TABLE CHI_TIET_HOA_DON_MUA_HANG (
    MACHITIET NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MAHOADONMUA NUMBER,
    MASANPHAM NUMBER,
    SOLUONG NUMBER,
    SOLUONGDANHAN NUMBER,
    DONGIA NUMBER(19,0),
    THANHTIEN NUMBER(19,0)
);


CREATE TABLE NHA_CUNG_CAP (
    MADOITAC NUMBER PRIMARY KEY,
    MASOTHEU NVARCHAR2(50) NOT NULL,
    DIEUKHOANTHANHTOAN NVARCHAR2(255) NOT NULL,
    GHICHU NVARCHAR2(500) NOT NULL
);