CREATE TABLE CUA_HANG (
    MACUAHANG NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TENCUAHANG NVARCHAR2(255) NOT NULL,
    DIACHI NVARCHAR2(500) NOT NULL,
    SODIENTHOAI NVARCHAR2(20) NOT NULL,
    QUANLY NUMBER NOT NULL
);

CREATE TABLE QUAN_LY_CHI_NHANH (
    MACUAHANG NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    PRIMARY KEY (MACUAHANG, MANHANVIEN)
);
