CREATE TABLE DANH_MUC (
    MADANHMUC NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TENDANHMUC NVARCHAR2(255) NOT NULL,
    MADANHMUCCHA NUMBER -- Khóa ngoại tham chiếu ngược lại chính bảng này
);

CREATE TABLE SAN_PHAM (
    MASANPHAM NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TENSANPHAM VARCHAR2(500) NOT NULL,
    DONVITINH NVARCHAR2(50) NOT NULL,
    GIANIEMYET NUMBER(19,0) NOT NULL,
    THUE FLOAT NOT NULL,
    MAVACH NVARCHAR2(100) NOT NULL,
    COTHEMUA NUMBER(1) NOT NULL, -- Boolean chuyển sang Number(1)
    COTHEBAN NUMBER(1) NOT NULL,
    POS NUMBER(1) NOT NULL,
    THUONGHIEU NVARCHAR2(255) NOT NULL,
    XUATXU NVARCHAR2(255) NOT NULL,
    PHUHOP NVARCHAR2(255) NOT NULL, -- Phù hợp cho loại da/đối tượng nào
    THANHPHAN CLOB NOT NULL,         -- Dùng CLOB cho nội dung dài
    HUONGDAN CLOB NOT NULL,
    MOTA CLOB NOT NULL
);

CREATE TABLE SAN_PHAM_DANH_MUC (
    MASANPHAM NUMBER NOT NULL,
    MADANHMUC NUMBER NOT NULL,
    PRIMARY KEY (MASANPHAM, MADANHMUC) -- Khóa chính hỗn hợp
);



INSERT INTO SAN_PHAM (
    TENSANPHAM, DONVITINH, GIANIEMYET, THUE, MAVACH, 
    COTHEMUA, COTHEBAN, POS, THUONGHIEU, XUATXU, 
    PHUHOP, THANHPHAN, HUONGDAN, MOTA
) 
VALUES (
    'Thức ăn mèo Whiskas', 'Gói', 50000, 0.1, '8931234567', 
    1, 1, 1, 'Whiskas', 'Mỹ', 
    'Mèo con', 'Cá hồi', 'Ăn trực tiếp', 'Thơm ngon bổ dưỡng'
);

COMMIT;
-- 2. CỰC KỲ QUAN TRỌNG: Bạn phải chạy lệnh này thì Backend mới thấy được dữ liệu
COMMIT;

select * from san_pham;