CREATE TABLE HOA_DON_BAN_HANG (
    MAHOADON NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MADOITAC NUMBER NOT NULL,
    MADONHANG NUMBER NOT NULL,
    MACUAHANG NUMBER NOT NULL,
    NGAYBAN TIMESTAMP NOT NULL,
    TONGTIEN NUMBER(19,0) NOT NULL,
    DIEMTICHDUOC NUMBER NOT NULL,
    DIEMSUDUNG NUMBER NOT NULL,
    PHUONGTHUCTHANHTHOAN NVARCHAR2(50) NOT NULL,
    MANHANVIEN NUMBER NOT NULL
);

CREATE TABLE CHI_TIET_HOA_DON_BAN_HANG (
    MACHITIET NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MASANPHAM NUMBER,
    MAHOADON NUMBER,
    SOLUONG NUMBER,
    DONGIA NUMBER(19,0),
    THANHTIEN NUMBER(19,0)
);

CREATE TABLE DON_HANG (
    MADONHANG NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MACUAHANG NUMBER NOT NULL,
    MADOITAC NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAYTAO TIMESTAMP NOT NULL,
    TONGTIENTAMTINH NUMBER(19,0) NOT NULL,
    DIEMMUONDUNG NUMBER NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL,
    GHICHU NVARCHAR2(500) NOT NULL
);

CREATE TABLE CHI_TIET_DON_HANG (
    MACHITIET NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MASANPHAM NUMBER,
    MADONHANG NUMBER,
    SOLUONG NUMBER,
    DONGIA NUMBER(19,0),
    THANHTIEN NUMBER(19,0)
);

CREATE TABLE DOI_TAC (
    MADOITAC NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TENDOITAC NVARCHAR2(255) NOT NULL,
    SODIENTHOAI NVARCHAR2(20),
    DIACHI NVARCHAR2(500),
    EMAIL NVARCHAR2(100),
    LOAIDOITAC NVARCHAR2(50)
);

CREATE TABLE KHACH_HANG (
    MADOITAC NUMBER PRIMARY KEY,
    DIEMTICHLUY NUMBER DEFAULT 0 NOT NULL,
    NGAYTHAMGIA DATE NOT NULL,
    LOAIKHACHHANG NVARCHAR2(50) DEFAULT 'Đồng' NOT NULL
);