CREATE TABLE TAI_KHOAN (
    MATAIKHOAN NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MACUAHANG NUMBER,
    TENTAIKHOAN NVARCHAR2(255) NOT NULL,
    LOAITAIKHOAN NVARCHAR2(50) NOT NULL,
    SOTAIKHOAN NVARCHAR2(50),
    TENNGANHANG NVARCHAR2(255),
    SODUHIENTAI NUMBER(19,0) NOT NULL,
    MUCDICH NVARCHAR2(100) NOT NULL
);

CREATE TABLE GIAO_DICH_TIEN (
    MAGIAODICH NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MACUAHANG NUMBER,
    MATAIKHOAN NUMBER NOT NULL,
    LOAIGIAODICH NVARCHAR2(100) NOT NULL,
    SOTIEN NUMBER(19,0) NOT NULL,
    NGAYGIAODICH TIMESTAMP NOT NULL,
    MAHOADONBAN NUMBER,
    MAHOADONMUA NUMBER,
    MAPHIEULUONG NUMBER,
    MAQUYETTOAN NUMBER,
    MATAIKHOANDOIUNG NUMBER,
    GHICHU NVARCHAR2(500) NOT NULL
);
