CREATE TABLE NHANVIEN (
    MANHANVIEN NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MACUAHANG NUMBER,
    HOTEN NVARCHAR2(255) NOT NULL,
    SDT NVARCHAR2(20) NOT NULL,
    EMAIL NVARCHAR2(100) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL
);

CREATE TABLE CHAM_CONG (
    MACHAMCONG NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MANHANVIEN NUMBER NOT NULL,
    NGAY DATE NOT NULL,
    GIOVAO TIMESTAMP NOT NULL,
    GIORA TIMESTAMP NOT NULL,
    SOGIOLAM FLOAT NOT NULL,
    TANGCA FLOAT DEFAULT 0 NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL,
    GHICHU NVARCHAR2(500) NOT NULL
);

CREATE TABLE QUAN_LY_PHEP (
    IDPHEP NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MANHANVIEN NUMBER NOT NULL,
    NAM NUMBER NOT NULL,
    TONGPHEP NUMBER NOT NULL,
    DADUNG NUMBER NOT NULL,
    CONLAI NUMBER NOT NULL
);

CREATE TABLE DON_XIN_NGHI_PHEP (
    MADON NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    MANHANVIEN NUMBER NOT NULL,
    LOAINGHI NVARCHAR2(50) NOT NULL,
    TUNGAY DATE NOT NULL,
    DENNGAY DATE NOT NULL,
    SONGAY NUMBER NOT NULL,
    LYDO NVARCHAR2(500) NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL,
    NGUOIDUYET NUMBER NOT NULL
);
