CREATE TABLE VAI_TRO (
    MAVAITRO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    TENVAITRO NVARCHAR2(100) NOT NULL,
    QUYENHAN CLOB NOT NULL -- JSON trong Oracle nên dùng CLOB hoặc JSON (từ 21c)
);

CREATE TABLE PHAN_QUYEN_NHAN_VIEN (
    MAVAITRO NUMBER NOT NULL,
    MANHANVIEN NUMBER NOT NULL,
    NGAYGAN DATE NOT NULL,
    PRIMARY KEY (MAVAITRO, MANHANVIEN)
);

CREATE TABLE TAI_KHOAN_NHAN_VIEN (
    MANHANVIEN NUMBER PRIMARY KEY,
    USERNAME NVARCHAR2(100) NOT NULL UNIQUE,
    PASSWORDHASD NVARCHAR2(255) NOT NULL,
    PASSWORDHASHHISTORY NVARCHAR2(1000) NOT NULL,
    NGAYTAO DATE NOT NULL,
    LAST_LOGIN TIMESTAMP NOT NULL,
    TRANG_THAI NUMBER(1) NOT NULL
);